/*******************************************************************************
Copyright © 2011 DuPont. All rights reserved. 
Author: Thomas Snyder
Email: thomas.snyder@usa.dupont.com, tom@3ddd.com
Description:  Trigger Handler for Solution
********************************************************************************/
public with sharing class SolutionHandler extends TriggerHandlerBase {
    /*******************************************************************************

    public override void bulkAfter() {  

        if (!Trigger.isDelete)
           SolutionDetails.SolutionAfterChange();-- KK to fix Compile error in Clean dev, this class is set for delete
        
     else
           SolutionDetails.SolutionAfterDelete(); -- KK to fix Compile error in Clean dev, this class is set for delete
        
    } 
    ********************************************************************************/

}