Aleutian Islands,33712,AK,United States@
Aleutians East Borough,33350,AK,United States@
Aleutians West Census Area,33262,AK,United States@
Anchorage Borough,33263,AK,United States@
Bethel Census Area,33264,AK,United States@
Bristol Bay Borough,33265,AK,United States@
Denali Borough,33713,AK,United States@
Dillingham Census Area,33266,AK,United States@
Fairbanks North Star Borough,33267,AK,United States@
Haines Borough,33268,AK,United States@
Juneau Borough,33269,AK,United States@
Kenai Peninsula Borough,33270,AK,United States@
Ketchikan Gateway Borough,33271,AK,United States@
Kodiak Island Borough,33272,AK,United States@
Lake and Peninsula Borough,33273,AK,United States@
Matanuska-Susitna Borough,33274,AK,United States@
Nome Census Area,33275,AK,United States@
North Slope Borough,33276,AK,United States@
Northwest Arctic Borough,33277,AK,United States@
Prince of Wales-Outer Ketchikan Census Area,33278,AK,United States@
Sitka Borough,33279,AK,United States@
Skagway-Yakutat-Angoon Census Area,33280,AK,United States@
Southeast Fairbanks Census Area,33281,AK,United States@
Valdez-Cordova Census Area,33282,AK,United States@
Wade Hampton Census Area,33283,AK,United States@
Wrangell-Petersburg Census Area,33284,AK,United States@
Yukon-Koyukuk Census Area,33285,AK,United States@
Autauga,295,AL,United States@
Baldwin,296,AL,United States@
Barbour,297,AL,United States@
Bibb,298,AL,United States@
Blount,299,AL,United States@
Bullock,300,AL,United States@
Butler,301,AL,United States@
Calhoun,302,AL,United States@
Chambers,303,AL,United States@
Cherokee,304,AL,United States@
Chilton,305,AL,United States@
Choctaw,306,AL,United States@
Clarke,307,AL,United States@
Clay,308,AL,United States@
Cleburne,309,AL,United States@
Coffee,310,AL,United States@
Colbert,311,AL,United States@
Conecuh,312,AL,United States@
Coosa,313,AL,United States@
Covington,314,AL,United States@
Crenshaw,315,AL,United States@
Cullman,316,AL,United States@
Dale,317,AL,United States@
Dallas,318,AL,United States@
DeKalb,319,AL,United States@
Elmore,320,AL,United States@
Escambia,321,AL,United States@
Etowah,322,AL,United States@
Fayette,323,AL,United States@
Franklin,324,AL,United States@
Geneva,325,AL,United States@
Greene,326,AL,United States@
Hale,327,AL,United States@
Henry,328,AL,United States@
Houston,329,AL,United States@
Jackson,330,AL,United States@
Jefferson,331,AL,United States@
Lamar,332,AL,United States@
Lauderdale,333,AL,United States@
Lawrence,334,AL,United States@
Lee,335,AL,United States@
Limestone,336,AL,United States@
Lowndes,337,AL,United States@
Macon,338,AL,United States@
Madison,339,AL,United States@
Marengo,340,AL,United States@
Marion,341,AL,United States@
Marshall,342,AL,United States@
Mobile,343,AL,United States@
Monroe,344,AL,United States@
Montgomery,345,AL,United States@
Morgan,346,AL,United States@
Perry,347,AL,United States@
Pickens,348,AL,United States@
Pike,349,AL,United States@
Randolph,350,AL,United States@
Russell,351,AL,United States@
Shelby,353,AL,United States@
St. Clair,352,AL,United States@
Sumter,354,AL,United States@
Talladega,355,AL,United States@
Tallapoosa,356,AL,United States@
Tuscaloosa,357,AL,United States@
Walker,358,AL,United States@
Washington,359,AL,United States@
Wilcox,360,AL,United States@
Winston,361,AL,United States@
Arkansas,362,AR,United States@
Ashley,363,AR,United States@
Baxter,364,AR,United States@
Benton,365,AR,United States@
Boone,366,AR,United States@
Bradley,367,AR,United States@
Calhoun,368,AR,United States@
Carroll,369,AR,United States@
Chicot,370,AR,United States@
Clark,371,AR,United States@
Clay,372,AR,United States@
Cleburne,373,AR,United States@
Cleveland,374,AR,United States@
Columbia,375,AR,United States@
Conway,376,AR,United States@
Craighead,377,AR,United States@
Crawford,378,AR,United States@
Crittenden,379,AR,United States@
Cross,380,AR,United States@
Dallas,381,AR,United States@
Desha,382,AR,United States@
Drew,383,AR,United States@
Faulkner,384,AR,United States@
Franklin,385,AR,United States@
Fulton,386,AR,United States@
Garland,387,AR,United States@
Grant,388,AR,United States@
Greene,389,AR,United States@
Hempstead,390,AR,United States@
Hot Spring,391,AR,United States@
Howard,392,AR,United States@
Independence,393,AR,United States@
Izard,394,AR,United States@
Jackson,395,AR,United States@
Jefferson,396,AR,United States@
Johnson,397,AR,United States@
Lafayette,398,AR,United States@
Lawrence,399,AR,United States@
Lee,400,AR,United States@
Lincoln,401,AR,United States@
Little River,402,AR,United States@
Logan,403,AR,United States@
Lonoke,404,AR,United States@
Madison,405,AR,United States@
Marion,406,AR,United States@
Miller,407,AR,United States@
Mississippi,408,AR,United States@
Monroe,409,AR,United States@
Montgomery,410,AR,United States@
Nevada,411,AR,United States@
Newton,412,AR,United States@
Ouachita,413,AR,United States@
Perry,414,AR,United States@
Phillips,415,AR,United States@
Pike,416,AR,United States@
Poinsett,417,AR,United States@
Polk,418,AR,United States@
Pope,419,AR,United States@
Prairie,420,AR,United States@
Pulaski,421,AR,United States@
Randolph,422,AR,United States@
Saline,424,AR,United States@
Scott,425,AR,United States@
Searcy,426,AR,United States@
Sebastian,427,AR,United States@
Sevier,428,AR,United States@
Sharp,429,AR,United States@
St. Francis,423,AR,United States@
Stone,430,AR,United States@
Texarkana,33708,AR,United States@
Union,431,AR,United States@
Van Buren,432,AR,United States@
Washington,433,AR,United States@
White,434,AR,United States@
Woodruff,435,AR,United States@
Yell,436,AR,United States@
Apache,437,AZ,United States@
Cochise,438,AZ,United States@
Coconino,439,AZ,United States@
Gila,440,AZ,United States@
Graham,441,AZ,United States@
Greenlee,442,AZ,United States@
La Paz,443,AZ,United States@
Maricopa,444,AZ,United States@
Mohave,445,AZ,United States@
Navajo,446,AZ,United States@
Pima,447,AZ,United States@
Pinal,448,AZ,United States@
Santa Cruz,449,AZ,United States@
Yavapai,450,AZ,United States@
Yuma,451,AZ,United States@
Alameda,452,CA,United States@
Alpine,453,CA,United States@
Amador,454,CA,United States@
Butte,455,CA,United States@
Calaveras,456,CA,United States@
Camp Roberts,222,CA,United States@
Colusa,457,CA,United States@
Contra Costa,458,CA,United States@
Del Norte,459,CA,United States@
Eastern LA,33359,CA,United States@
El Dorado,460,CA,United States@
Fresno,461,CA,United States@
Glenn,462,CA,United States@
Humboldt,463,CA,United States@
Imperial,464,CA,United States@
Inyo,465,CA,United States@
Kern,466,CA,United States@
Kings,467,CA,United States@
Lake,468,CA,United States@
Lassen,469,CA,United States@
Lemoore Naval AS,223,CA,United States@
Los Angeles,470,CA,United States@
Madera,471,CA,United States@
Marin,472,CA,United States@
Mariposa,473,CA,United States@
Mendocino,474,CA,United States@
Merced,475,CA,United States@
Modoc,476,CA,United States@
Mono,477,CA,United States@
Monterey,478,CA,United States@
Napa,479,CA,United States@
Nevada,480,CA,United States@
Northern LA,33360,CA,United States@
Orange,481,CA,United States@
Placer,482,CA,United States@
Plumas,483,CA,United States@
Riverside,484,CA,United States@
Sacramento,485,CA,United States@
San Benito,486,CA,United States@
San Bernardino,487,CA,United States@
San Diego,488,CA,United States@
San Francisco,489,CA,United States@
San Joaquin,490,CA,United States@
San Luis Obispo,491,CA,United States@
San Mateo,492,CA,United States@
Santa Barbara,493,CA,United States@
Santa Clara,494,CA,United States@
Santa Cruz,495,CA,United States@
Shasta,496,CA,United States@
Sierra,497,CA,United States@
Siskiyou,498,CA,United States@
Solano,499,CA,United States@
Sonoma,500,CA,United States@
Southern LA,33362,CA,United States@
Stanislaus,501,CA,United States@
Sutter,502,CA,United States@
Tehama,503,CA,United States@
Trinity,504,CA,United States@
Tulare,505,CA,United States@
Tuolumne,506,CA,United States@
Ventura,507,CA,United States@
Western LA,33361,CA,United States@
Yolo,508,CA,United States@
Yuba,509,CA,United States@
Adams,510,CO,United States@
Alamosa,511,CO,United States@
Arapahoe,512,CO,United States@
Archuleta,513,CO,United States@
Aurora,3613,CO,United States@
Baca,514,CO,United States@
Bent,515,CO,United States@
Boulder,516,CO,United States@
Chaffee,517,CO,United States@
Cheyenne,518,CO,United States@
Clear Creek,519,CO,United States@
Conejos,520,CO,United States@
Costilla,521,CO,United States@
Crowley,522,CO,United States@
Custer,523,CO,United States@
Delta,524,CO,United States@
Denver,525,CO,United States@
Dolores,526,CO,United States@
Douglas,527,CO,United States@
Eagle,528,CO,United States@
El Paso,530,CO,United States@
Elbert,529,CO,United States@
Fremont,531,CO,United States@
Garfield,532,CO,United States@
Gilpin,533,CO,United States@
Grand,534,CO,United States@
Gunnison,535,CO,United States@
Hinsdale,536,CO,United States@
Huerfano,537,CO,United States@
Jackson,538,CO,United States@
Jefferson,539,CO,United States@
Kiowa,540,CO,United States@
Kit Carson,541,CO,United States@
La Plata,543,CO,United States@
Lake,542,CO,United States@
Larimer,544,CO,United States@
Las Animas,545,CO,United States@
Lemoore Naval AS,223,CO,United States@
Lincoln,546,CO,United States@
Logan,547,CO,United States@
Mesa,548,CO,United States@
Mineral,549,CO,United States@
Moffat,550,CO,United States@
Montezuma,551,CO,United States@
Montrose,552,CO,United States@
Morgan,553,CO,United States@
Otero,554,CO,United States@
Ouray,555,CO,United States@
Park,556,CO,United States@
Phillips,557,CO,United States@
Pitkin,558,CO,United States@
Prowers,559,CO,United States@
Pueblo,560,CO,United States@
Rio Blanco,561,CO,United States@
Rio Grande,562,CO,United States@
Routt,563,CO,United States@
Saguache,564,CO,United States@
San Juan,565,CO,United States@
San Miguel,566,CO,United States@
Sedgwick,567,CO,United States@
Summit,568,CO,United States@
Teller,569,CO,United States@
Washington,570,CO,United States@
Weld,571,CO,United States@
Yuma,572,CO,United States@
Fairfield,573,CT,United States@
Hartford,574,CT,United States@
Litchfield,575,CT,United States@
Middlesex,576,CT,United States@
New Haven,577,CT,United States@
New London,578,CT,United States@
S.W. Fairfield,33690,CT,United States@
Tolland,579,CT,United States@
Windham,580,CT,United States@
District of Columbia,33689,DC,United States@
Kent,581,DE,United States@
New Castle,582,DE,United States@
Sussex,583,DE,United States@
Alachua,584,FL,United States@
Baker,585,FL,United States@
Bay,586,FL,United States@
Bradford,587,FL,United States@
Brevard,588,FL,United States@
Broward,589,FL,United States@
Calhoun,590,FL,United States@
Charlotte,591,FL,United States@
Citrus,592,FL,United States@
Clay,593,FL,United States@
Collier,594,FL,United States@
Columbia,595,FL,United States@
Dade,596,FL,United States@
DeSoto,597,FL,United States@
Dixie,598,FL,United States@
Duval,599,FL,United States@
Escambia,600,FL,United States@
Flagler,601,FL,United States@
Franklin,602,FL,United States@
Gadsden,603,FL,United States@
Gilchrist,604,FL,United States@
Glades,605,FL,United States@
Gulf,606,FL,United States@
Hamilton,607,FL,United States@
Hardee,608,FL,United States@
Hendry,609,FL,United States@
Hernando,610,FL,United States@
Highlands,611,FL,United States@
Hillsborough,612,FL,United States@
Holmes,613,FL,United States@
Indian River,614,FL,United States@
Jackson,615,FL,United States@
Jefferson,616,FL,United States@
Lafayette,617,FL,United States@
Lake,618,FL,United States@
Lee,619,FL,United States@
Leon,620,FL,United States@
Levy,621,FL,United States@
Liberty,622,FL,United States@
Madison,623,FL,United States@
Manatee,624,FL,United States@
Marion,625,FL,United States@
Martin,626,FL,United States@
Monroe,627,FL,United States@
Nassau,628,FL,United States@
Okaloosa,629,FL,United States@
Okeechobee,630,FL,United States@
Orange,631,FL,United States@
Osceola,632,FL,United States@
Palm Beach,633,FL,United States@
Pasco,634,FL,United States@
Pinellas,635,FL,United States@
Polk,636,FL,United States@
Putnam,637,FL,United States@
Santa Rosa,640,FL,United States@
Sarasota,641,FL,United States@
Seminole,642,FL,United States@
St. Johns,638,FL,United States@
St. Lucie,639,FL,United States@
Sumter,643,FL,United States@
Suwannee,644,FL,United States@
Taylor,645,FL,United States@
Union,646,FL,United States@
Volusia,647,FL,United States@
Wakulla,648,FL,United States@
Walton,649,FL,United States@
Washington,650,FL,United States@
Appling,651,GA,United States@
Atkinson,652,GA,United States@
Atlanta,3655,GA,United States@
Bacon,653,GA,United States@
Baker,654,GA,United States@
Baldwin,655,GA,United States@
Banks,656,GA,United States@
Barrow,657,GA,United States@
Bartow,658,GA,United States@
Ben Hill,659,GA,United States@
Berrien,660,GA,United States@
Bibb,661,GA,United States@
Bleckley,662,GA,United States@
Brantley,663,GA,United States@
Brooks,664,GA,United States@
Bryan,665,GA,United States@
Bulloch,666,GA,United States@
Burke,667,GA,United States@
Butts,668,GA,United States@
Calhoun,669,GA,United States@
Camden,670,GA,United States@
Candler,671,GA,United States@
Carroll,672,GA,United States@
Catoosa,673,GA,United States@
Charlton,674,GA,United States@
Chatham,675,GA,United States@
Chattahoochee,676,GA,United States@
Chattooga,677,GA,United States@
Cherokee,678,GA,United States@
Clarke,679,GA,United States@
Clay,680,GA,United States@
Clayton,681,GA,United States@
Clinch,682,GA,United States@
Cobb,683,GA,United States@
Coffee,684,GA,United States@
College Park,33746,GA,United States@
Colquitt,685,GA,United States@
Columbia,686,GA,United States@
Cook,687,GA,United States@
Coweta,688,GA,United States@
Crawford,689,GA,United States@
Crisp,690,GA,United States@
Dade,691,GA,United States@
Dawson,692,GA,United States@
Decatur,693,GA,United States@
DeKalb,694,GA,United States@
Dodge,695,GA,United States@
Dooly,696,GA,United States@
Dougherty,697,GA,United States@
Douglas,698,GA,United States@
Early,699,GA,United States@
Echols,700,GA,United States@
Effingham,701,GA,United States@
Elbert,702,GA,United States@
Emanuel,703,GA,United States@
Evans,704,GA,United States@
Fannin,705,GA,United States@
Fayette,706,GA,United States@
Floyd,707,GA,United States@
Forsyth,708,GA,United States@
Franklin,709,GA,United States@
Fulton,710,GA,United States@
Gilmer,711,GA,United States@
Glascock,712,GA,United States@
Glynn,713,GA,United States@
Gordon,714,GA,United States@
Grady,715,GA,United States@
Greene,716,GA,United States@
Gwinnett,717,GA,United States@
Habersham,718,GA,United States@
Hall,719,GA,United States@
Hancock,720,GA,United States@
Haralson,721,GA,United States@
Harris,722,GA,United States@
Hart,723,GA,United States@
Heard,724,GA,United States@
Henry,725,GA,United States@
Houston,726,GA,United States@
Irwin,727,GA,United States@
Jackson,728,GA,United States@
Jasper,729,GA,United States@
Jeff Davis,730,GA,United States@
Jefferson,731,GA,United States@
Jenkins,732,GA,United States@
Johnson,733,GA,United States@
Jones,734,GA,United States@
Lamar,735,GA,United States@
Lanier,736,GA,United States@
Laurens,737,GA,United States@
Lee,738,GA,United States@
Liberty,739,GA,United States@
Lincoln,740,GA,United States@
Long,741,GA,United States@
Lowndes,742,GA,United States@
Lumpkin,743,GA,United States@
Macon,746,GA,United States@
Madison,747,GA,United States@
Marion,748,GA,United States@
McDuffie,744,GA,United States@
McIntosh,745,GA,United States@
Meriwether,749,GA,United States@
Miller,750,GA,United States@
Mitchell,751,GA,United States@
Monroe,752,GA,United States@
Montgomery,753,GA,United States@
Morgan,754,GA,United States@
Murray,755,GA,United States@
Muscogee,756,GA,United States@
Newton,757,GA,United States@
Oconee,758,GA,United States@
Oglethorpe,759,GA,United States@
Paulding,760,GA,United States@
Peach,761,GA,United States@
Pickens,762,GA,United States@
Pierce,763,GA,United States@
Pike,764,GA,United States@
Polk,765,GA,United States@
Pulaski,766,GA,United States@
Putnam,767,GA,United States@
Quitman,768,GA,United States@
Rabun,769,GA,United States@
Randolph,770,GA,United States@
Richmond,771,GA,United States@
Rockdale,772,GA,United States@
Schley,773,GA,United States@
Screven,774,GA,United States@
Seminole,775,GA,United States@
Spalding,776,GA,United States@
Stephens,777,GA,United States@
Stewart,778,GA,United States@
Sumter,779,GA,United States@
Talbot,780,GA,United States@
Taliaferro,781,GA,United States@
Tattnall,782,GA,United States@
Taylor,783,GA,United States@
Telfair,784,GA,United States@
Terrell,785,GA,United States@
Thomas,786,GA,United States@
Tift,787,GA,United States@
Toombs,788,GA,United States@
Towns,789,GA,United States@
Treutlen,790,GA,United States@
Troup,791,GA,United States@
Turner,792,GA,United States@
Twiggs,793,GA,United States@
Union,794,GA,United States@
Upson,795,GA,United States@
Walker,796,GA,United States@
Walton,797,GA,United States@
Ware,798,GA,United States@
Warren,799,GA,United States@
Washington,800,GA,United States@
Wayne,801,GA,United States@
Webster,802,GA,United States@
Wheeler,803,GA,United States@
White,804,GA,United States@
Whitfield,805,GA,United States@
Wilcox,806,GA,United States@
Wilkes,807,GA,United States@
Wilkinson,808,GA,United States@
Worth,809,GA,United States@
Hawaii,810,HI,United States@
Honolulu,811,HI,United States@
Kalawao,812,HI,United States@
Kauai,813,HI,United States@
Maui,814,HI,United States@
Adair,815,IA,United States@
Adams,816,IA,United States@
Allamakee,817,IA,United States@
Appanoose,818,IA,United States@
Audubon,819,IA,United States@
Benton,820,IA,United States@
Black Hawk,821,IA,United States@
Boone,822,IA,United States@
Bremer,823,IA,United States@
Buchanan,824,IA,United States@
Buena Vista,825,IA,United States@
Butler,826,IA,United States@
Calhoun,827,IA,United States@
Carroll,828,IA,United States@
Cass,829,IA,United States@
Cedar,830,IA,United States@
Cerro Gordo,831,IA,United States@
Cherokee,832,IA,United States@
Chickasaw,833,IA,United States@
Clarke,834,IA,United States@
Clay,835,IA,United States@
Clayton,836,IA,United States@
Clinton,837,IA,United States@
Crawford,838,IA,United States@
Dallas,839,IA,United States@
Davis,840,IA,United States@
Decatur,841,IA,United States@
Delaware,842,IA,United States@
Des Moines,843,IA,United States@
Dickinson,844,IA,United States@
Dubuque,845,IA,United States@
Emmet,846,IA,United States@
Fayette,847,IA,United States@
Floyd,848,IA,United States@
Franklin,849,IA,United States@
Fremont,850,IA,United States@
Greene,851,IA,United States@
Grundy,852,IA,United States@
Guthrie,853,IA,United States@
Hamilton,854,IA,United States@
Hancock,855,IA,United States@
Hardin,856,IA,United States@
Harrison,857,IA,United States@
Henry,858,IA,United States@
Howard,859,IA,United States@
Humboldt,860,IA,United States@
Ida,861,IA,United States@
Iowa,862,IA,United States@
Jackson,863,IA,United States@
Jasper,864,IA,United States@
Jefferson,865,IA,United States@
Johnson,866,IA,United States@
Jones,867,IA,United States@
Keokuk,868,IA,United States@
Kossuth,869,IA,United States@
Lee,870,IA,United States@
Linn,871,IA,United States@
Louisa,872,IA,United States@
Lucas,873,IA,United States@
Lyon,874,IA,United States@
Madison,875,IA,United States@
Mahaska,876,IA,United States@
Marion,877,IA,United States@
Marshall,878,IA,United States@
Mills,879,IA,United States@
Mitchell,880,IA,United States@
Monona,881,IA,United States@
Monroe,882,IA,United States@
Montgomery,883,IA,United States@
Muscatine,884,IA,United States@
O'Brien,885,IA,United States@
Osceola,886,IA,United States@
Page,887,IA,United States@
Palo Alto,888,IA,United States@
Plymouth,889,IA,United States@
Pocahontas,890,IA,United States@
Polk,891,IA,United States@
Pottawattamie,892,IA,United States@
Poweshiek,893,IA,United States@
Ringgold,894,IA,United States@
Sac,895,IA,United States@
Scott,896,IA,United States@
Shelby,897,IA,United States@
Sioux,898,IA,United States@
Story,899,IA,United States@
Tama,900,IA,United States@
Taylor,901,IA,United States@
Union,902,IA,United States@
Van Buren,903,IA,United States@
Wapello,904,IA,United States@
Warren,905,IA,United States@
Washington,906,IA,United States@
Wayne,907,IA,United States@
Webster,908,IA,United States@
Winnebago,909,IA,United States@
Winneshiek,910,IA,United States@
Woodbury,911,IA,United States@
Worth,912,IA,United States@
Wright,913,IA,United States@
Ada,914,ID,United States@
Adams,915,ID,United States@
Bannock,916,ID,United States@
Bear Lake,917,ID,United States@
Benewah,918,ID,United States@
Bingham,919,ID,United States@
Blaine,920,ID,United States@
Boise,921,ID,United States@
Bonner,922,ID,United States@
Bonneville,923,ID,United States@
Boundary,924,ID,United States@
Butte,925,ID,United States@
Camas,926,ID,United States@
Canyon,927,ID,United States@
Caribou,928,ID,United States@
Cassia,929,ID,United States@
Clark,930,ID,United States@
Clearwater,931,ID,United States@
Custer,932,ID,United States@
Elmore,933,ID,United States@
Franklin,934,ID,United States@
Fremont,935,ID,United States@
Gem,936,ID,United States@
Gooding,937,ID,United States@
Idaho,938,ID,United States@
Jefferson,939,ID,United States@
Jerome,940,ID,United States@
Kootenai,941,ID,United States@
Latah,942,ID,United States@
Lemhi,943,ID,United States@
Lewis,944,ID,United States@
Lincoln,945,ID,United States@
Madison,946,ID,United States@
Minidoka,947,ID,United States@
Nez Perce,948,ID,United States@
Oneida,949,ID,United States@
Owyhee,950,ID,United States@
Payette,951,ID,United States@
Power,952,ID,United States@
Shoshone,953,ID,United States@
Teton,954,ID,United States@
Twin Falls,955,ID,United States@
Valley,956,ID,United States@
Washington,957,ID,United States@
Adams,958,IL,United States@
Alexander,959,IL,United States@
Bensenville,38803,IL,United States@
Bond,960,IL,United States@
Boone,961,IL,United States@
Brown,962,IL,United States@
Bureau,963,IL,United States@
Calhoun,964,IL,United States@
Carroll,965,IL,United States@
Cass,966,IL,United States@
Centralia,33722,IL,United States@
Champaign,967,IL,United States@
Christian,968,IL,United States@
City of Chicago - North,33355,IL,United States@
City of Chicago - South,33354,IL,United States@
Clark,969,IL,United States@
Clay,970,IL,United States@
Clinton,971,IL,United States@
Coles,972,IL,United States@
Collinsville,33723,IL,United States@
Cook,973,IL,United States@
Crawford,974,IL,United States@
Cumberland,975,IL,United States@
De Witt,977,IL,United States@
Deerfield,33724,IL,United States@
DeKalb,976,IL,United States@
Douglas,978,IL,United States@
DuPage,979,IL,United States@
Edgar,980,IL,United States@
Edwards,981,IL,United States@
Effingham,982,IL,United States@
Elgin,3688,IL,United States@
Fayette,983,IL,United States@
Ford,984,IL,United States@
Franklin,985,IL,United States@
Fulton,986,IL,United States@
Gallatin,987,IL,United States@
Greene,988,IL,United States@
Grundy,989,IL,United States@
Hamilton,990,IL,United States@
Hancock,991,IL,United States@
Hardin,992,IL,United States@
Henderson,993,IL,United States@
Henry,994,IL,United States@
Hinsdale,33728,IL,United States@
Iroquois,995,IL,United States@
Jackson,996,IL,United States@
Jasper,997,IL,United States@
Jefferson,998,IL,United States@
Jersey,999,IL,United States@
Jo Daviess,1000,IL,United States@
Johnson,1001,IL,United States@
Kane,1002,IL,United States@
Kankakee,1003,IL,United States@
Kendall,1004,IL,United States@
Knox,1005,IL,United States@
La Salle,1007,IL,United States@
Lake,1006,IL,United States@
Lawrence,1008,IL,United States@
Lee,1009,IL,United States@
Livingston,1010,IL,United States@
Logan,1011,IL,United States@
Macon,1015,IL,United States@
Macoupin,1016,IL,United States@
Madison,1017,IL,United States@
Marion,1018,IL,United States@
Marshall,1019,IL,United States@
Mason,1020,IL,United States@
Massac,1021,IL,United States@
McDonough,1012,IL,United States@
McHenry,1013,IL,United States@
McLean,1014,IL,United States@
Menard,1022,IL,United States@
Mercer,1023,IL,United States@
Monroe,1024,IL,United States@
Montgomery,1025,IL,United States@
Morgan,1026,IL,United States@
Moultrie,1027,IL,United States@
North Cook,33356,IL,United States@
Ogle,1028,IL,United States@
Peoria,1029,IL,United States@
Perry,1030,IL,United States@
Piatt,1031,IL,United States@
Pike,1032,IL,United States@
Pope,1033,IL,United States@
Pulaski,1034,IL,United States@
Putnam,1035,IL,United States@
Randolph,1036,IL,United States@
Richland,1037,IL,United States@
Rock Island,1038,IL,United States@
Saline,1040,IL,United States@
Sangamon,1041,IL,United States@
Schuyler,1042,IL,United States@
Scott,1043,IL,United States@
Shelby,1044,IL,United States@
South Cook,33358,IL,United States@
St. Clair,1039,IL,United States@
Stark,1045,IL,United States@
Stephenson,1046,IL,United States@
Streator,33740,IL,United States@
Tazewell,1047,IL,United States@
Union,1048,IL,United States@
Vermilion,1049,IL,United States@
Wabash,1050,IL,United States@
Warren,1051,IL,United States@
Washington,1052,IL,United States@
Wayne,1053,IL,United States@
Western Cook,33357,IL,United States@
White,1054,IL,United States@
Whiteside,1055,IL,United States@
Will,1056,IL,United States@
Williamson,1057,IL,United States@
Winnebago,1058,IL,United States@
Woodford,1059,IL,United States@
Adams,1060,IN,United States@
Allen,1061,IN,United States@
Bartholomew,1062,IN,United States@
Benton,1063,IN,United States@
Blackford,1064,IN,United States@
Boone,1065,IN,United States@
Brown,1066,IN,United States@
Carroll,1067,IN,United States@
Cass,1068,IN,United States@
Clark,1069,IN,United States@
Clay,1070,IN,United States@
Clinton,1071,IN,United States@
Crawford,1072,IN,United States@
Daviess,1073,IN,United States@
De Kalb,1076,IN,United States@
Dearborn,1074,IN,United States@
Decatur,1075,IN,United States@
Delaware,1077,IN,United States@
Dubois,1078,IN,United States@
Elkhart,1079,IN,United States@
Fayette,1080,IN,United States@
Floyd,1081,IN,United States@
Fountain,1082,IN,United States@
Franklin,1083,IN,United States@
Fulton,1084,IN,United States@
Gibson,1085,IN,United States@
Grant,1086,IN,United States@
Greene,1087,IN,United States@
Hamilton,1088,IN,United States@
Hancock,1089,IN,United States@
Harrison,1090,IN,United States@
Hendricks,1091,IN,United States@
Henry,1092,IN,United States@
Howard,1093,IN,United States@
Huntington,1094,IN,United States@
Jackson,1095,IN,United States@
Jasper,1096,IN,United States@
Jay,1097,IN,United States@
Jefferson,1098,IN,United States@
Jennings,1099,IN,United States@
Johnson,1100,IN,United States@
Knox,1101,IN,United States@
Kosciusko,1102,IN,United States@
La Porte,1105,IN,United States@
Lagrange,1103,IN,United States@
Lake,1104,IN,United States@
Lawrence,1106,IN,United States@
Madison,1107,IN,United States@
Marion,1108,IN,United States@
Marshall,1109,IN,United States@
Martin,1110,IN,United States@
Miami,1111,IN,United States@
Monroe,1112,IN,United States@
Montgomery,1113,IN,United States@
Morgan,1114,IN,United States@
Newton,1115,IN,United States@
Noble,1116,IN,United States@
Ohio,1117,IN,United States@
Orange,1118,IN,United States@
Owen,1119,IN,United States@
Parke,1120,IN,United States@
Perry,1121,IN,United States@
Pike,1122,IN,United States@
Porter,1123,IN,United States@
Posey,1124,IN,United States@
Pulaski,1125,IN,United States@
Putnam,1126,IN,United States@
Randolph,1127,IN,United States@
Ripley,1128,IN,United States@
Rush,1129,IN,United States@
Scott,1131,IN,United States@
Shelby,1132,IN,United States@
Spencer,1133,IN,United States@
St. Joseph,1130,IN,United States@
Starke,1134,IN,United States@
Steuben,1135,IN,United States@
Sullivan,1136,IN,United States@
Switzerland,1137,IN,United States@
Tippecanoe,1138,IN,United States@
Tipton,1139,IN,United States@
Union,1140,IN,United States@
Vanderburgh,1141,IN,United States@
Vermillion,1142,IN,United States@
Vigo,1143,IN,United States@
Wabash,1144,IN,United States@
Warren,1145,IN,United States@
Warrick,1146,IN,United States@
Washington,1147,IN,United States@
Wayne,1148,IN,United States@
Wells,1149,IN,United States@
White,1150,IN,United States@
Whitley,1151,IN,United States@
Allen,1152,KS,United States@
Anderson,1153,KS,United States@
Atchison,1154,KS,United States@
Barber,1155,KS,United States@
Barton,1156,KS,United States@
Bourbon,1157,KS,United States@
Brown,1158,KS,United States@
Butler,1159,KS,United States@
Chase,1160,KS,United States@
Chautauqua,1161,KS,United States@
Cherokee,1162,KS,United States@
Cheyenne,1163,KS,United States@
Clark,1164,KS,United States@
Clay,1165,KS,United States@
Cloud,1166,KS,United States@
Coffey,1167,KS,United States@
Comanche,1168,KS,United States@
Cowley,1169,KS,United States@
Crawford,1170,KS,United States@
Decatur,1171,KS,United States@
Dickinson,1172,KS,United States@
Doniphan,1173,KS,United States@
Douglas,1174,KS,United States@
Edwards,1175,KS,United States@
Elk,1176,KS,United States@
Ellis,1177,KS,United States@
Ellsworth,1178,KS,United States@
Finney,1179,KS,United States@
Ford,1180,KS,United States@
Fort Riley,56745,KS,United States@
Franklin,1181,KS,United States@
Geary,1182,KS,United States@
Gove,1183,KS,United States@
Graham,1184,KS,United States@
Grant,1185,KS,United States@
Gray,1186,KS,United States@
Greeley,1187,KS,United States@
Greenwood,1188,KS,United States@
Hamilton,1189,KS,United States@
Harper,1190,KS,United States@
Harvey,1191,KS,United States@
Haskell,1192,KS,United States@
Hodgeman,1193,KS,United States@
Jackson,1194,KS,United States@
Jefferson,1195,KS,United States@
Jewell,1196,KS,United States@
Johnson,1197,KS,United States@
Kearny,1198,KS,United States@
Kingman,1199,KS,United States@
Kiowa,1200,KS,United States@
Labette,1201,KS,United States@
Lane,1202,KS,United States@
Leavenworth,1203,KS,United States@
Lincoln,1204,KS,United States@
Linn,1205,KS,United States@
Logan,1206,KS,United States@
Lyon,1207,KS,United States@
Marion,1209,KS,United States@
Marshall,1210,KS,United States@
McPherson,1208,KS,United States@
Meade,1211,KS,United States@
Miami,1212,KS,United States@
Mitchell,1213,KS,United States@
Montgomery,1214,KS,United States@
Morris,1215,KS,United States@
Morton,1216,KS,United States@
Nemaha,1217,KS,United States@
Neosho,1218,KS,United States@
Ness,1219,KS,United States@
Norton,1220,KS,United States@
Osage,1221,KS,United States@
Osborne,1222,KS,United States@
Ottawa,1223,KS,United States@
Pawnee,1224,KS,United States@
Phillips,1225,KS,United States@
Pottawatomie,1226,KS,United States@
Pratt,1227,KS,United States@
Rawlins,1228,KS,United States@
Reno,1229,KS,United States@
Republic,1230,KS,United States@
Rice,1231,KS,United States@
Riley,1232,KS,United States@
Rooks,1233,KS,United States@
Rush,1234,KS,United States@
Russell,1235,KS,United States@
Saline,1236,KS,United States@
Scott,1237,KS,United States@
Sedgwick,1238,KS,United States@
Seward,1239,KS,United States@
Shawnee,1240,KS,United States@
Sheridan,1241,KS,United States@
Sherman,1242,KS,United States@
Smith,1243,KS,United States@
Stafford,1244,KS,United States@
Stanton,1245,KS,United States@
Stevens,1246,KS,United States@
Sumner,1247,KS,United States@
Thomas,1248,KS,United States@
Trego,1249,KS,United States@
Wabaunsee,1250,KS,United States@
Wallace,1251,KS,United States@
Washington,1252,KS,United States@
Wichita,1253,KS,United States@
Wilson,1254,KS,United States@
Woodson,1255,KS,United States@
Wyandotte,1256,KS,United States@
Adair,1257,KY,United States@
Allen,1258,KY,United States@
Anderson,1259,KY,United States@
Ballard,1260,KY,United States@
Barren,1261,KY,United States@
Bath,1262,KY,United States@
Bell,1263,KY,United States@
Boone,1264,KY,United States@
Bourbon,1265,KY,United States@
Boyd,1266,KY,United States@
Boyle,1267,KY,United States@
Bracken,1268,KY,United States@
Breathitt,1269,KY,United States@
Breckinridge,1270,KY,United States@
Bullitt,1271,KY,United States@
Butler,1272,KY,United States@
Caldwell,1273,KY,United States@
Calloway,1274,KY,United States@
Campbell,1275,KY,United States@
Carlisle,1276,KY,United States@
Carroll,1277,KY,United States@
Carter,1278,KY,United States@
Casey,1279,KY,United States@
Christian,1280,KY,United States@
Clark,1281,KY,United States@
Clay,1282,KY,United States@
Clinton,1283,KY,United States@
Crittenden,1284,KY,United States@
Cumberland,1285,KY,United States@
Daviess,1286,KY,United States@
Edmonson,1287,KY,United States@
Elliott,1288,KY,United States@
Estill,1289,KY,United States@
Fayette,1290,KY,United States@
Fleming,1291,KY,United States@
Floyd,1292,KY,United States@
Franklin,1293,KY,United States@
Fulton,1294,KY,United States@
Gallatin,1295,KY,United States@
Garrard,1296,KY,United States@
Grant,1297,KY,United States@
Graves,1298,KY,United States@
Grayson,1299,KY,United States@
Green,1300,KY,United States@
Greenup,1301,KY,United States@
Hancock,1302,KY,United States@
Hardin,1303,KY,United States@
Harlan,1304,KY,United States@
Harrison,1305,KY,United States@
Hart,1306,KY,United States@
Henderson,1307,KY,United States@
Henry,1308,KY,United States@
Hickman,1309,KY,United States@
Hopkins,1310,KY,United States@
Jackson,1311,KY,United States@
Jefferson,1312,KY,United States@
Jessamine,1313,KY,United States@
Johnson,1314,KY,United States@
Kenton,1315,KY,United States@
Knott,1316,KY,United States@
Knox,1317,KY,United States@
Larue,1318,KY,United States@
Laurel,1319,KY,United States@
Lawrence,1320,KY,United States@
Lee,1321,KY,United States@
Leslie,1322,KY,United States@
Letcher,1323,KY,United States@
Lewis,1324,KY,United States@
Lincoln,1325,KY,United States@
Livingston,1326,KY,United States@
Logan,1327,KY,United States@
Lyon,1328,KY,United States@
Madison,1332,KY,United States@
Magoffin,1333,KY,United States@
Marion,1334,KY,United States@
Marshall,1335,KY,United States@
Martin,1336,KY,United States@
Mason,1337,KY,United States@
McCracken,1329,KY,United States@
McCreary,1330,KY,United States@
McLean,1331,KY,United States@
Meade,1338,KY,United States@
Menifee,1339,KY,United States@
Mercer,1340,KY,United States@
Metcalfe,1341,KY,United States@
Monroe,1342,KY,United States@
Montgomery,1343,KY,United States@
Morgan,1344,KY,United States@
Muhlenberg,1345,KY,United States@
Nelson,1346,KY,United States@
Nicholas,1347,KY,United States@
Ohio,1348,KY,United States@
Oldham,1349,KY,United States@
Owen,1350,KY,United States@
Owsley,1351,KY,United States@
Pendleton,1352,KY,United States@
Perry,1353,KY,United States@
Pike,1354,KY,United States@
Powell,1355,KY,United States@
Pulaski,1356,KY,United States@
Robertson,1357,KY,United States@
Rockcastle,1358,KY,United States@
Rowan,1359,KY,United States@
Russell,1360,KY,United States@
Scott,1361,KY,United States@
Shelby,1362,KY,United States@
Simpson,1363,KY,United States@
Spencer,1364,KY,United States@
Taylor,1365,KY,United States@
Todd,1366,KY,United States@
Trigg,1367,KY,United States@
Trimble,1368,KY,United States@
Union,1369,KY,United States@
Warren,1370,KY,United States@
Washington,1371,KY,United States@
Wayne,1372,KY,United States@
Webster,1373,KY,United States@
Whitley,1374,KY,United States@
Wolfe,1375,KY,United States@
Woodford,1376,KY,United States@
Acadia Parish,33286,LA,United States@
Allen Parish,33287,LA,United States@
Ascension Parish,33288,LA,United States@
Assumption Parish,33289,LA,United States@
Avoyelles Parish,33290,LA,United States@
Beauregard Parish,33291,LA,United States@
Bienville Parish,33292,LA,United States@
Bossier Parish,33293,LA,United States@
Caddo Parish,33294,LA,United States@
Calcasieu Parish,33295,LA,United States@
Caldwell Parish,33296,LA,United States@
Cameron Parish,33297,LA,United States@
Catahoula Parish,33298,LA,United States@
Claiborne Parish,33299,LA,United States@
Concordia Parish,33300,LA,United States@
De Soto Parish,33301,LA,United States@
East Baton Rouge Parish,33302,LA,United States@
East Carroll Parish,33303,LA,United States@
East Feliciana Parish,33304,LA,United States@
Evangeline Parish,33305,LA,United States@
Franklin Parish,33306,LA,United States@
Grant Parish,33307,LA,United States@
Iberia Parish,33308,LA,United States@
Iberville Parish,33309,LA,United States@
Jackson Parish,33310,LA,United States@
Jefferson Davis Parish,33312,LA,United States@
Jefferson Parish,33311,LA,United States@
La Salle Parish,33315,LA,United States@
Lafayette Parish,33313,LA,United States@
Lafourche Parish,33314,LA,United States@
Lincoln Parish,33316,LA,United States@
Livingston Parish,33317,LA,United States@
Madison Parish,33318,LA,United States@
Morehouse Parish,33319,LA,United States@
Natchitoches Parish,33320,LA,United States@
Orleans Parish,33321,LA,United States@
Ouachita Parish,33322,LA,United States@
Plaquemines Parish,33323,LA,United States@
Pointe Coupee Parish,33324,LA,United States@
Rapides Parish,33325,LA,United States@
Red River Parish,33326,LA,United States@
Richland Parish,33327,LA,United States@
Sabine Parish,33328,LA,United States@
Shreveport,3743,LA,United States@
St. Bernard Parish,33329,LA,United States@
St. Charles Parish,33330,LA,United States@
St. Helena Parish,33331,LA,United States@
St. James Parish,33332,LA,United States@
St. John the Baptist Parish,33333,LA,United States@
St. Landry Parish,33334,LA,United States@
St. Martin Parish,33335,LA,United States@
St. Mary Parish,33336,LA,United States@
St. Tammany Parish,33337,LA,United States@
Tangipahoa Parish,33338,LA,United States@
Tensas Parish,33339,LA,United States@
Terrebonne Parish,33340,LA,United States@
Union Parish,33341,LA,United States@
Vermilion Parish,33342,LA,United States@
Vernon Parish,33343,LA,United States@
Washington Parish,33344,LA,United States@
Webster Parish,33345,LA,United States@
West Baton Rouge Parish,33346,LA,United States@
West Carroll Parish,33347,LA,United States@
West Feliciana Parish,33348,LA,United States@
Winn Parish,33349,LA,United States@
Barnstable,1377,MA,United States@
Berkshire,1378,MA,United States@
Bristol,1379,MA,United States@
Dukes,1380,MA,United States@
Essex,1381,MA,United States@
Franklin,1382,MA,United States@
Hampden,1383,MA,United States@
Hampshire,1384,MA,United States@
Middlesex,1385,MA,United States@
Nantucket,1386,MA,United States@
Norfolk,1387,MA,United States@
Plymouth,1388,MA,United States@
Suffolk,1389,MA,United States@
Worcester,1390,MA,United States@
Allegany,1391,MD,United States@
Anne Arundel,1392,MD,United States@
Baltimore,1393,MD,United States@
Baltimore,33688,MD,United States@
Calvert,1394,MD,United States@
Caroline,1395,MD,United States@
Carroll,1396,MD,United States@
Cecil,1397,MD,United States@
Charles,1398,MD,United States@
Dorchester,1399,MD,United States@
Frederick,1400,MD,United States@
Garrett,1401,MD,United States@
Harford,1402,MD,United States@
Howard,1403,MD,United States@
Kent,1404,MD,United States@
Montgomery,1405,MD,United States@
Prince George's,1406,MD,United States@
Queen Anne's,1407,MD,United States@
Somerset,1409,MD,United States@
St. Mary's,1408,MD,United States@
Talbot,1410,MD,United States@
Washington,1411,MD,United States@
Wicomico,1412,MD,United States@
Worcester,1413,MD,United States@
Androscoggin,1414,ME,United States@
Aroostook,1415,ME,United States@
Cumberland,1416,ME,United States@
Franklin,1417,ME,United States@
Hancock,1418,ME,United States@
Kennebec,1419,ME,United States@
Knox,1420,ME,United States@
Lincoln,1421,ME,United States@
Oxford,1422,ME,United States@
Penobscot,1423,ME,United States@
Piscataquis,1424,ME,United States@
Sagadahoc,1425,ME,United States@
Somerset,1426,ME,United States@
Waldo,1427,ME,United States@
Washington,1428,ME,United States@
York,1429,ME,United States@
Alcona,1430,MI,United States@
Alger,1431,MI,United States@
Allegan,1432,MI,United States@
Alpena,1433,MI,United States@
Antrim,1434,MI,United States@
Arenac,1435,MI,United States@
Baraga,1436,MI,United States@
Barry,1437,MI,United States@
Bay,1438,MI,United States@
Benzie,1439,MI,United States@
Berrien,1440,MI,United States@
Branch,1441,MI,United States@
Calhoun,1442,MI,United States@
Cass,1443,MI,United States@
Charlevoix,1444,MI,United States@
Cheboygan,1445,MI,United States@
Chippewa,1446,MI,United States@
Clare,1447,MI,United States@
Clinton,1448,MI,United States@
Crawford,1449,MI,United States@
Delta,1450,MI,United States@
Dickinson,1451,MI,United States@
Eaton,1452,MI,United States@
Emmet,1453,MI,United States@
Genesee,1454,MI,United States@
Gladwin,1455,MI,United States@
Gogebic,1456,MI,United States@
Grand Traverse,1457,MI,United States@
Gratiot,1458,MI,United States@
Hillsdale,1459,MI,United States@
Holland City,33697,MI,United States@
Houghton,1460,MI,United States@
Huron,1461,MI,United States@
Ingham,1462,MI,United States@
Ionia,1463,MI,United States@
Iosco,1464,MI,United States@
Iron,1465,MI,United States@
Isabella,1466,MI,United States@
Jackson,1467,MI,United States@
Kalamazoo,1468,MI,United States@
Kalkaska,1469,MI,United States@
Kent,1470,MI,United States@
Keweenaw,1471,MI,United States@
Lake,1472,MI,United States@
Lapeer,1473,MI,United States@
Leelanau,1474,MI,United States@
Lenawee,1475,MI,United States@
Livingston,1476,MI,United States@
Luce,1477,MI,United States@
Mackinac,1478,MI,United States@
Macomb,1479,MI,United States@
Manistee,1480,MI,United States@
Marquette,1481,MI,United States@
Mason,1482,MI,United States@
Mecosta,1483,MI,United States@
Menominee,1484,MI,United States@
Midland,1485,MI,United States@
Missaukee,1486,MI,United States@
Monroe,1487,MI,United States@
Montcalm,1488,MI,United States@
Montmorency,1489,MI,United States@
Muskegon,1490,MI,United States@
Newaygo,1491,MI,United States@
Oakland,1492,MI,United States@
Oceana,1493,MI,United States@
Ogemaw,1494,MI,United States@
Ontonagon,1495,MI,United States@
Osceola,1496,MI,United States@
Oscoda,1497,MI,United States@
Otsego,1498,MI,United States@
Ottawa,1499,MI,United States@
Presque Isle,1500,MI,United States@
Roscommon,1501,MI,United States@
Saginaw,1502,MI,United States@
Sanilac,1505,MI,United States@
Schoolcraft,1506,MI,United States@
Shiawassee,1507,MI,United States@
St. Clair,1503,MI,United States@
St. Joseph,1504,MI,United States@
Tuscola,1508,MI,United States@
Van Buren,1509,MI,United States@
Washtenaw,1510,MI,United States@
Wayne,1511,MI,United States@
Wayne,43913,MI,United States@
Wexford,1512,MI,United States@
Aitkin,1513,MN,United States@
Anoka,1514,MN,United States@
Becker,1515,MN,United States@
Beltrami,1516,MN,United States@
Benton,1517,MN,United States@
Big Stone,1518,MN,United States@
Blaine,33719,MN,United States@
Blue Earth,1519,MN,United States@
Brown,1520,MN,United States@
Carlton,1521,MN,United States@
Carver,1522,MN,United States@
Cass,1523,MN,United States@
Chippewa,1524,MN,United States@
Chisago,1525,MN,United States@
Clay,1526,MN,United States@
Clearwater,1527,MN,United States@
Cook,1528,MN,United States@
Cottonwood,1529,MN,United States@
Crow Wing,1530,MN,United States@
Dakota,1531,MN,United States@
Dodge,1532,MN,United States@
Douglas,1533,MN,United States@
Faribault,1534,MN,United States@
Fillmore,1535,MN,United States@
Freeborn,1536,MN,United States@
Goodhue,1537,MN,United States@
Grant,1538,MN,United States@
Hennepin,1539,MN,United States@
Houston,1540,MN,United States@
Hubbard,1541,MN,United States@
Isanti,1542,MN,United States@
Itasca,1543,MN,United States@
Jackson,1544,MN,United States@
Kanabec,1545,MN,United States@
Kandiyohi,1546,MN,United States@
Kittson,1547,MN,United States@
Koochiching,1548,MN,United States@
Lac qui Parle,1549,MN,United States@
Lake of the Woods,1551,MN,United States@
Lake,1550,MN,United States@
Le Sueur,1552,MN,United States@
Lincoln,1553,MN,United States@
Lyon,1554,MN,United States@
Mahnomen,1556,MN,United States@
Marshall,1557,MN,United States@
Martin,1558,MN,United States@
McLeod,1555,MN,United States@
Meeker,1559,MN,United States@
Mille Lacs,1560,MN,United States@
Morrison,1561,MN,United States@
Mower,1562,MN,United States@
Murray,1563,MN,United States@
Nicollet,1564,MN,United States@
Nobles,1565,MN,United States@
Norman,1566,MN,United States@
Olmsted,1567,MN,United States@
Otter Tail,1568,MN,United States@
Pennington,1569,MN,United States@
Pine,1570,MN,United States@
Pipestone,1571,MN,United States@
Polk,1572,MN,United States@
Pope,1573,MN,United States@
Ramsey,1574,MN,United States@
Red Lake,1575,MN,United States@
Redwood,1576,MN,United States@
Renville,1577,MN,United States@
Rice,1578,MN,United States@
Rock,1579,MN,United States@
Roseau,1580,MN,United States@
Saint Anthony,33739,MN,United States@
Saint Cloud,33696,MN,United States@
Scott,1582,MN,United States@
Sherburne,1583,MN,United States@
Sibley,1584,MN,United States@
St. Louis,1581,MN,United States@
Stearns,1585,MN,United States@
Steele,1586,MN,United States@
Stevens,1587,MN,United States@
Swift,1588,MN,United States@
Todd,1589,MN,United States@
Traverse,1590,MN,United States@
Wabasha,1591,MN,United States@
Wadena,1592,MN,United States@
Waseca,1593,MN,United States@
Washington,1594,MN,United States@
Watonwan,1595,MN,United States@
White Bear Lake,33743,MN,United States@
Wilkin,1596,MN,United States@
Winona,1597,MN,United States@
Wright,1598,MN,United States@
Yellow Medicine,1599,MN,United States@
Adair,1600,MO,United States@
Andrew,1601,MO,United States@
Atchison,1602,MO,United States@
Audrain,1603,MO,United States@
Barry,1604,MO,United States@
Barton,1605,MO,United States@
Bates,1606,MO,United States@
Benton,1607,MO,United States@
Bollinger,1608,MO,United States@
Boone,1609,MO,United States@
Buchanan,1610,MO,United States@
Butler,1611,MO,United States@
Caldwell,1612,MO,United States@
Callaway,1613,MO,United States@
Camden,1614,MO,United States@
Cape Girardeau,1615,MO,United States@
Carroll,1616,MO,United States@
Carter,1617,MO,United States@
Cass,1618,MO,United States@
Cedar,1619,MO,United States@
Chariton,1620,MO,United States@
Christian,1621,MO,United States@
Clark,1622,MO,United States@
Clay,1623,MO,United States@
Clinton,1624,MO,United States@
Cole,1625,MO,United States@
Cooper,1626,MO,United States@
Crawford,1627,MO,United States@
Dade,1628,MO,United States@
Dallas,1629,MO,United States@
Daviess,1630,MO,United States@
DeKalb,1631,MO,United States@
Dent,1632,MO,United States@
Douglas,1633,MO,United States@
Dunklin,1634,MO,United States@
Franklin,1635,MO,United States@
Gasconade,1636,MO,United States@
Gentry,1637,MO,United States@
Greene,1638,MO,United States@
Grundy,1639,MO,United States@
Hannibal,33729,MO,United States@
Harrison,1640,MO,United States@
Henry,1641,MO,United States@
Hickory,1642,MO,United States@
Holt,1643,MO,United States@
Howard,1644,MO,United States@
Howell,1645,MO,United States@
Iron,1646,MO,United States@
Jackson,1647,MO,United States@
Jasper,1648,MO,United States@
Jefferson,1649,MO,United States@
Jefferson,33731,MO,United States@
Johnson,1650,MO,United States@
Joplin,33732,MO,United States@
Kansas,33747,MO,United States@
Knox,1651,MO,United States@
Laclede,1652,MO,United States@
Lafayette,1653,MO,United States@
Lawrence,1654,MO,United States@
Lewis,1655,MO,United States@
Lincoln,1656,MO,United States@
Linn,1657,MO,United States@
Livingston,1658,MO,United States@
Macon,1660,MO,United States@
Madison,1661,MO,United States@
Maries,1662,MO,United States@
Marion,1663,MO,United States@
McDonald,1659,MO,United States@
Mercer,1664,MO,United States@
Miller,1665,MO,United States@
Mississippi,1666,MO,United States@
Moniteau,1667,MO,United States@
Monroe,1668,MO,United States@
Montgomery,1669,MO,United States@
Morgan,1670,MO,United States@
New Madrid,1671,MO,United States@
Newton,1672,MO,United States@
Nodaway,1673,MO,United States@
Oregon,1674,MO,United States@
Osage,1675,MO,United States@
Ozark,1676,MO,United States@
Pemiscot,1677,MO,United States@
Perry,1678,MO,United States@
Pettis,1679,MO,United States@
Phelps,1680,MO,United States@
Pike,1681,MO,United States@
Platte,1682,MO,United States@
Polk,1683,MO,United States@
Pulaski,1684,MO,United States@
Putnam,1685,MO,United States@
Ralls,1686,MO,United States@
Randolph,1687,MO,United States@
Ray,1688,MO,United States@
Reynolds,1689,MO,United States@
Richards,45750,MO,United States@
Ripley,1690,MO,United States@
Saline,1696,MO,United States@
Schuyler,1697,MO,United States@
Scotland,1698,MO,United States@
Scott,1699,MO,United States@
Shannon,1700,MO,United States@
Shelby,1701,MO,United States@
Sikeston,45813,MO,United States@
St. Charles,1691,MO,United States@
St. Clair,1692,MO,United States@
St. Francois,1694,MO,United States@
St. Louis,1695,MO,United States@
St. Louis,33692,MO,United States@
Ste. Genevieve,1693,MO,United States@
Stoddard,1702,MO,United States@
Stone,1703,MO,United States@
Sullivan,1704,MO,United States@
Taney,1705,MO,United States@
Texas,1706,MO,United States@
Vernon,1707,MO,United States@
Warren,1708,MO,United States@
Washington,1709,MO,United States@
Wayne,1710,MO,United States@
Webster,1711,MO,United States@
Worth,1712,MO,United States@
Wright,1713,MO,United States@
Adams,1714,MS,United States@
Alcorn,1715,MS,United States@
Amite,1716,MS,United States@
Attala,1717,MS,United States@
Benton,1718,MS,United States@
Bolivar,1719,MS,United States@
Calhoun,1720,MS,United States@
Carroll,1721,MS,United States@
Chickasaw,1722,MS,United States@
Choctaw,1723,MS,United States@
Claiborne,1724,MS,United States@
Clarke,1725,MS,United States@
Clay,1726,MS,United States@
Coahoma,1727,MS,United States@
Copiah,1728,MS,United States@
Covington,1729,MS,United States@
DeSoto,1730,MS,United States@
Forrest,1731,MS,United States@
Franklin,1732,MS,United States@
George,1733,MS,United States@
Greene,1734,MS,United States@
Grenada,1735,MS,United States@
Hancock,1736,MS,United States@
Harrison,1737,MS,United States@
Hinds,1738,MS,United States@
Holmes,1739,MS,United States@
Humphreys,1740,MS,United States@
Issaquena,1741,MS,United States@
Itawamba,1742,MS,United States@
Jackson,1743,MS,United States@
Jasper,1744,MS,United States@
Jefferson Davis,1746,MS,United States@
Jefferson,1745,MS,United States@
Jones,1747,MS,United States@
Kemper,1748,MS,United States@
Lafayette,1749,MS,United States@
Lamar,1750,MS,United States@
Lauderdale,1751,MS,United States@
Lawrence,1752,MS,United States@
Leake,1753,MS,United States@
Lee,1754,MS,United States@
Leflore,1755,MS,United States@
Lincoln,1756,MS,United States@
Lowndes,1757,MS,United States@
Madison,1758,MS,United States@
Marion,1759,MS,United States@
Marshall,1760,MS,United States@
Monroe,1761,MS,United States@
Montgomery,1762,MS,United States@
Neshoba,1763,MS,United States@
Newton,1764,MS,United States@
Noxubee,1765,MS,United States@
Oktibbeha,1766,MS,United States@
Panola,1767,MS,United States@
Pearl River,1768,MS,United States@
Perry,1769,MS,United States@
Pike,1770,MS,United States@
Pontotoc,1771,MS,United States@
Prentiss,1772,MS,United States@
Quitman,1773,MS,United States@
Rankin,1774,MS,United States@
Scott,1775,MS,United States@
Sharkey,1776,MS,United States@
Simpson,1777,MS,United States@
Smith,1778,MS,United States@
Stone,1779,MS,United States@
Sunflower,1780,MS,United States@
Tallahatchie,1781,MS,United States@
Tate,1782,MS,United States@
Tippah,1783,MS,United States@
Tishomingo,1784,MS,United States@
Tunica,1785,MS,United States@
Union,1786,MS,United States@
Walthall,1787,MS,United States@
Warren,1788,MS,United States@
Washington,1789,MS,United States@
Wayne,1790,MS,United States@
Webster,1791,MS,United States@
Wilkinson,1792,MS,United States@
Winston,1793,MS,United States@
Yalobusha,1794,MS,United States@
Yazoo,1795,MS,United States@
Beaverhead,1796,MT,United States@
Big Horn,1797,MT,United States@
Blaine,1798,MT,United States@
Broadwater,1799,MT,United States@
Carbon,1800,MT,United States@
Carter,1801,MT,United States@
Cascade,1802,MT,United States@
Chouteau,1803,MT,United States@
Custer,1804,MT,United States@
Daniels,1805,MT,United States@
Dawson,1806,MT,United States@
Deer Lodge,1807,MT,United States@
Fallon,1808,MT,United States@
Fergus,1809,MT,United States@
Flathead,1810,MT,United States@
Gallatin,1811,MT,United States@
Garfield,1812,MT,United States@
Glacier,1813,MT,United States@
Golden Valley,1814,MT,United States@
Granite,1815,MT,United States@
Hill,1816,MT,United States@
Jefferson,1817,MT,United States@
Judith Basin,1818,MT,United States@
Lake,1819,MT,United States@
Lewis and Clark,1820,MT,United States@
Liberty,1821,MT,United States@
Lincoln,1822,MT,United States@
Madison,1824,MT,United States@
McCone,1823,MT,United States@
Meagher,1825,MT,United States@
Mineral,1826,MT,United States@
Missoula,1827,MT,United States@
Musselshell,1828,MT,United States@
Park,1829,MT,United States@
Petroleum,1830,MT,United States@
Phillips,1831,MT,United States@
Pondera,1832,MT,United States@
Powder River,1833,MT,United States@
Powell,1834,MT,United States@
Prairie,1835,MT,United States@
Ravalli,1836,MT,United States@
Richland,1837,MT,United States@
Roosevelt,1838,MT,United States@
Rosebud,1839,MT,United States@
Sanders,1840,MT,United States@
Sheridan,1841,MT,United States@
Silver Bow,1842,MT,United States@
Stillwater,1843,MT,United States@
Sweet Grass,1844,MT,United States@
Teton,1845,MT,United States@
Toole,1846,MT,United States@
Treasure,1847,MT,United States@
Valley,1848,MT,United States@
Wheatland,1849,MT,United States@
Wibaux,1850,MT,United States@
Yellowstone,1851,MT,United States@
Alamance,1852,NC,United States@
Alexander,1853,NC,United States@
Alleghany,1854,NC,United States@
Anson,1855,NC,United States@
Ashe,1856,NC,United States@
Avery,1857,NC,United States@
Beaufort,1858,NC,United States@
Bertie,1859,NC,United States@
Bladen,1860,NC,United States@
Brunswick,1861,NC,United States@
Buncombe,1862,NC,United States@
Burke,1863,NC,United States@
Cabarrus,1864,NC,United States@
Caldwell,1865,NC,United States@
Camden,1866,NC,United States@
Carteret,1867,NC,United States@
Caswell,1868,NC,United States@
Catawba,1869,NC,United States@
Chatham,1870,NC,United States@
Cherokee,1871,NC,United States@
Chowan,1872,NC,United States@
Clay,1873,NC,United States@
Cleveland,1874,NC,United States@
Columbus,1875,NC,United States@
Craven,1876,NC,United States@
Cumberland,1877,NC,United States@
Currituck,1878,NC,United States@
Dare,1879,NC,United States@
Davidson,1880,NC,United States@
Davie,1881,NC,United States@
Duplin,1882,NC,United States@
Durham,1883,NC,United States@
Edgecombe,1884,NC,United States@
Forsyth,1885,NC,United States@
Franklin,1886,NC,United States@
Gaston,1887,NC,United States@
Gates,1888,NC,United States@
Graham,1889,NC,United States@
Granville,1890,NC,United States@
Greene,1891,NC,United States@
Guilford,1892,NC,United States@
Halifax,1893,NC,United States@
Harnett,1894,NC,United States@
Haywood,1895,NC,United States@
Henderson,1896,NC,United States@
Hertford,1897,NC,United States@
Hoke,1898,NC,United States@
Hyde,1899,NC,United States@
Iredell,1900,NC,United States@
Jackson,1901,NC,United States@
Johnston,1902,NC,United States@
Jones,1903,NC,United States@
Kannapolis,33733,NC,United States@
Lee,1904,NC,United States@
Lenoir,1905,NC,United States@
Lincoln,1906,NC,United States@
Macon,1908,NC,United States@
Madison,1909,NC,United States@
Martin,1910,NC,United States@
McDowell,1907,NC,United States@
Mecklenburg,1911,NC,United States@
Mitchell,1912,NC,United States@
Montgomery,1913,NC,United States@
Moore,1914,NC,United States@
Nash,1915,NC,United States@
New Hanover,1916,NC,United States@
Northampton,1917,NC,United States@
Onslow,1918,NC,United States@
Orange,1919,NC,United States@
Pamlico,1920,NC,United States@
Pasquotank,1921,NC,United States@
Pender,1922,NC,United States@
Perquimans,1923,NC,United States@
Person,1924,NC,United States@
Pitt,1925,NC,United States@
Polk,1926,NC,United States@
Randolph,1927,NC,United States@
Richmond,1928,NC,United States@
Robeson,1929,NC,United States@
Rockingham,1930,NC,United States@
Rocky Mount,33738,NC,United States@
Rowan,1931,NC,United States@
Rutherford,1932,NC,United States@
Sampson,1933,NC,United States@
Scotland,1934,NC,United States@
Stanly,1935,NC,United States@
Stokes,1936,NC,United States@
Surry,1937,NC,United States@
Swain,1938,NC,United States@
Transylvania,1939,NC,United States@
Tyrrell,1940,NC,United States@
Union,1941,NC,United States@
Vance,1942,NC,United States@
Wake,1943,NC,United States@
Warren,1944,NC,United States@
Washington,1945,NC,United States@
Watauga,1946,NC,United States@
Wayne,1947,NC,United States@
Wilkes,1948,NC,United States@
Wilson,1949,NC,United States@
Yadkin,1950,NC,United States@
Yancey,1951,NC,United States@
Adams,1952,ND,United States@
Barnes,1953,ND,United States@
Benson,1954,ND,United States@
Billings,1955,ND,United States@
Bottineau,1956,ND,United States@
Bowman,1957,ND,United States@
Burke,1958,ND,United States@
Burleigh,1959,ND,United States@
Cass,1960,ND,United States@
Cavalier,1961,ND,United States@
Dickey,1962,ND,United States@
Divide,1963,ND,United States@
Dunn,1964,ND,United States@
Eddy,1965,ND,United States@
Emmons,1966,ND,United States@
Foster,1967,ND,United States@
Golden Valley,1968,ND,United States@
Grand Forks,1969,ND,United States@
Grant,1970,ND,United States@
Griggs,1971,ND,United States@
Hettinger,1972,ND,United States@
Kidder,1973,ND,United States@
LaMoure,1974,ND,United States@
Logan,1975,ND,United States@
McHenry,1976,ND,United States@
McIntosh,1977,ND,United States@
McKenzie,1978,ND,United States@
McLean,1979,ND,United States@
Mercer,1980,ND,United States@
Morton,1981,ND,United States@
Mountrail,1982,ND,United States@
Nelson,1983,ND,United States@
Oliver,1984,ND,United States@
Pembina,1985,ND,United States@
Pierce,1986,ND,United States@
Ramsey,1987,ND,United States@
Ransom,1988,ND,United States@
Renville,1989,ND,United States@
Richland,1990,ND,United States@
Rolette,1991,ND,United States@
Sargent,1992,ND,United States@
Sheridan,1993,ND,United States@
Sioux,1994,ND,United States@
Slope,1995,ND,United States@
Stark,1996,ND,United States@
Steele,1997,ND,United States@
Stutsman,1998,ND,United States@
Towner,1999,ND,United States@
Traill,2000,ND,United States@
Walsh,2001,ND,United States@
Ward,2002,ND,United States@
Wells,2003,ND,United States@
Williams,2004,ND,United States@
Adams,2005,NE,United States@
Antelope,2006,NE,United States@
Arthur,2007,NE,United States@
Banner,2008,NE,United States@
Blaine,2009,NE,United States@
Boone,2010,NE,United States@
Box Butte,2011,NE,United States@
Boyd,2012,NE,United States@
Brown,2013,NE,United States@
Buffalo,2014,NE,United States@
Burt,2015,NE,United States@
Butler,2016,NE,United States@
Cass,2017,NE,United States@
Cedar,2018,NE,United States@
Chase,2019,NE,United States@
Cherry,2020,NE,United States@
Cheyenne,2021,NE,United States@
Clay,2022,NE,United States@
Colfax,2023,NE,United States@
Cuming,2024,NE,United States@
Custer,2025,NE,United States@
Dakota,2026,NE,United States@
Dawes,2027,NE,United States@
Dawson,2028,NE,United States@
Deuel,2029,NE,United States@
Dixon,2030,NE,United States@
Dodge,2031,NE,United States@
Douglas,2032,NE,United States@
Dundy,2033,NE,United States@
Fillmore,2034,NE,United States@
Franklin,2035,NE,United States@
Frontier,2036,NE,United States@
Furnas,2037,NE,United States@
Gage,2038,NE,United States@
Garden,2039,NE,United States@
Garfield,2040,NE,United States@
Gosper,2041,NE,United States@
Grant,2042,NE,United States@
Greeley,2043,NE,United States@
Hall,2044,NE,United States@
Hamilton,2045,NE,United States@
Harlan,2046,NE,United States@
Hayes,2047,NE,United States@
Hitchcock,2048,NE,United States@
Holt,2049,NE,United States@
Hooker,2050,NE,United States@
Howard,2051,NE,United States@
Jefferson,2052,NE,United States@
Johnson,2053,NE,United States@
Kearney,2054,NE,United States@
Keith,2055,NE,United States@
Keya Paha,2056,NE,United States@
Kimball,2057,NE,United States@
Knox,2058,NE,United States@
Lancaster,2059,NE,United States@
Lincoln,2060,NE,United States@
Logan,2061,NE,United States@
Loup,2062,NE,United States@
Madison,2064,NE,United States@
McPherson,2063,NE,United States@
Merrick,2065,NE,United States@
Morrill,2066,NE,United States@
Nance,2067,NE,United States@
Nemaha,2068,NE,United States@
Nuckolls,2069,NE,United States@
Otoe,2070,NE,United States@
Pawnee,2071,NE,United States@
Perkins,2072,NE,United States@
Phelps,2073,NE,United States@
Pierce,2074,NE,United States@
Platte,2075,NE,United States@
Polk,2076,NE,United States@
Red Willow,2077,NE,United States@
Richardson,2078,NE,United States@
Rock,2079,NE,United States@
Saline,2080,NE,United States@
Sarpy,2081,NE,United States@
Saunders,2082,NE,United States@
Scotts Bluff,2083,NE,United States@
Seward,2084,NE,United States@
Sheridan,2085,NE,United States@
Sherman,2086,NE,United States@
Sioux,2087,NE,United States@
Stanton,2088,NE,United States@
Thayer,2089,NE,United States@
Thomas,2090,NE,United States@
Thurston,2091,NE,United States@
Valley,2092,NE,United States@
Washington,2093,NE,United States@
Wayne,2094,NE,United States@
Webster,2095,NE,United States@
Wheeler,2096,NE,United States@
York,2097,NE,United States@
Belknap,2098,NH,United States@
Carroll,2099,NH,United States@
Cheshire,2100,NH,United States@
Coos,2101,NH,United States@
Grafton,2102,NH,United States@
Hillsborough,2103,NH,United States@
Merrimack,2104,NH,United States@
Rockingham,2105,NH,United States@
Strafford,2106,NH,United States@
Sullivan,2107,NH,United States@
Atlantic,2108,NJ,United States@
Bergen,2109,NJ,United States@
Burlington,2110,NJ,United States@
Camden,2111,NJ,United States@
Cape May,2112,NJ,United States@
Cumberland,2113,NJ,United States@
Essex,2114,NJ,United States@
Gloucester,2115,NJ,United States@
Hudson,2116,NJ,United States@
Hunterdon,2117,NJ,United States@
Mercer,2118,NJ,United States@
Middlesex,2119,NJ,United States@
Monmouth,2120,NJ,United States@
Morris,2121,NJ,United States@
Ocean,2122,NJ,United States@
Passaic,2123,NJ,United States@
Salem,2124,NJ,United States@
Somerset,2125,NJ,United States@
Sussex,2126,NJ,United States@
Union,2127,NJ,United States@
Warren,2128,NJ,United States@
Bernalillo,2129,NM,United States@
Catron,2130,NM,United States@
Chaves,2131,NM,United States@
Cibola,2132,NM,United States@
Colfax,2133,NM,United States@
Curry,2134,NM,United States@
DeBaca,2135,NM,United States@
Dona Ana,2136,NM,United States@
Eddy,2137,NM,United States@
Grant,2138,NM,United States@
Guadalupe,2139,NM,United States@
Harding,2140,NM,United States@
Hidalgo,2141,NM,United States@
Lea,2142,NM,United States@
Lincoln,2143,NM,United States@
Los Alamos,2144,NM,United States@
Luna,2145,NM,United States@
McKinley,2146,NM,United States@
Mora,2147,NM,United States@
Otero,2148,NM,United States@
Quay,2149,NM,United States@
Rio Arriba,2150,NM,United States@
Roosevelt,2151,NM,United States@
San Juan,2153,NM,United States@
San Miguel,2154,NM,United States@
Sandoval,2152,NM,United States@
Santa Fe,2155,NM,United States@
Sierra,2156,NM,United States@
Socorro,2157,NM,United States@
Taos,2158,NM,United States@
Torrance,2159,NM,United States@
Union,2160,NM,United States@
Valencia,2161,NM,United States@
Carson City,3762,NV,United States@
Churchill,2162,NV,United States@
Clark,2163,NV,United States@
Douglas,2164,NV,United States@
Elko,2165,NV,United States@
Esmeralda,2166,NV,United States@
Eureka,2167,NV,United States@
Humboldt,2168,NV,United States@
Lander,2169,NV,United States@
Lincoln,2170,NV,United States@
Lyon,2171,NV,United States@
Mineral,2172,NV,United States@
Nye,2173,NV,United States@
Pershing,2174,NV,United States@
Storey,2175,NV,United States@
Washoe,2176,NV,United States@
White Pine,2177,NV,United States@
Albany,2178,NY,United States@
Allegany,2179,NY,United States@
Bronx,2180,NY,United States@
Broome,2181,NY,United States@
Cattaraugus,2182,NY,United States@
Cayuga,2183,NY,United States@
Chautauqua,2184,NY,United States@
Chemung,2185,NY,United States@
Chenango,2186,NY,United States@
Clinton,2187,NY,United States@
Columbia,2188,NY,United States@
Cortland,2189,NY,United States@
Delaware,2190,NY,United States@
Dutchess,2191,NY,United States@
Erie,2192,NY,United States@
Essex,2193,NY,United States@
Franklin,2194,NY,United States@
Fulton,2195,NY,United States@
Genesee,2196,NY,United States@
Greene,2197,NY,United States@
Hamilton,2198,NY,United States@
Herkimer,2199,NY,United States@
Jefferson,2200,NY,United States@
Kings,2201,NY,United States@
Lewis,2202,NY,United States@
Livingston,2203,NY,United States@
Madison,2204,NY,United States@
Monroe,2205,NY,United States@
Montgomery,2206,NY,United States@
Nassau,2207,NY,United States@
New York,2208,NY,United States@
Niagara,2209,NY,United States@
Oneida,2210,NY,United States@
Onondaga,2211,NY,United States@
Ontario,2212,NY,United States@
Orange,2213,NY,United States@
Orleans,2214,NY,United States@
Oswego,2215,NY,United States@
Otsego,2216,NY,United States@
Putnam,2217,NY,United States@
Queens,2218,NY,United States@
Rensselaer,2219,NY,United States@
Richmond,2220,NY,United States@
Rockland,2221,NY,United States@
Saratoga,2223,NY,United States@
Schenectady,2224,NY,United States@
Schoharie,2225,NY,United States@
Schuyler,2226,NY,United States@
Seneca,2227,NY,United States@
St. Lawrence,2222,NY,United States@
Steuben,2228,NY,United States@
Suffolk,2229,NY,United States@
Sullivan,2230,NY,United States@
Tioga,2231,NY,United States@
Tompkins,2232,NY,United States@
Ulster,2233,NY,United States@
Warren,2234,NY,United States@
Washington,2235,NY,United States@
Wayne,2236,NY,United States@
Westchester,2237,NY,United States@
Wyoming,2238,NY,United States@
Yates,2239,NY,United States@
Adams,2240,OH,United States@
Allen,2241,OH,United States@
Alliance,33714,OH,United States@
Ashland,2242,OH,United States@
Ashtabula,2243,OH,United States@
Athens,2244,OH,United States@
Auglaize,2245,OH,United States@
Belmont,2246,OH,United States@
Brown,2247,OH,United States@
Butler,2248,OH,United States@
Carroll,2249,OH,United States@
Champaign,2250,OH,United States@
Clark,2251,OH,United States@
Clermont,2252,OH,United States@
Clinton,2253,OH,United States@
Columbiana,2254,OH,United States@
Coshocton,2255,OH,United States@
Crawford,2256,OH,United States@
Cuyahoga,2257,OH,United States@
Darke,2258,OH,United States@
Defiance,2259,OH,United States@
Delaware,2260,OH,United States@
Erie,2261,OH,United States@
Fairfield,2262,OH,United States@
Fayette,2263,OH,United States@
Fostoria,33707,OH,United States@
Franklin,2264,OH,United States@
Fulton,2265,OH,United States@
Gallia,2266,OH,United States@
Geauga,2267,OH,United States@
Greene,2268,OH,United States@
Guernsey,2269,OH,United States@
Hamilton,2270,OH,United States@
Hancock,2271,OH,United States@
Hardin,2272,OH,United States@
Harrison,2273,OH,United States@
Henry,2274,OH,United States@
Highland,2275,OH,United States@
Hocking,2276,OH,United States@
Holmes,2277,OH,United States@
Huron,2278,OH,United States@
Jackson,2279,OH,United States@
Jefferson,2280,OH,United States@
Knox,2281,OH,United States@
Lake,2282,OH,United States@
Lawrence,2283,OH,United States@
Licking,2284,OH,United States@
Logan,2285,OH,United States@
Lorain,2286,OH,United States@
Lucas,2287,OH,United States@
Madison,2288,OH,United States@
Mahoning,2289,OH,United States@
Marion,2290,OH,United States@
Medina,2291,OH,United States@
Meigs,2292,OH,United States@
Mercer,2293,OH,United States@
Miami,2294,OH,United States@
Monroe,2295,OH,United States@
Montgomery,2296,OH,United States@
Morgan,2297,OH,United States@
Morrow,2298,OH,United States@
Muskingum,2299,OH,United States@
Noble,2300,OH,United States@
Ottawa,2301,OH,United States@
Paulding,2302,OH,United States@
Perry,2303,OH,United States@
Pickaway,2304,OH,United States@
Pike,2305,OH,United States@
Portage,2306,OH,United States@
Preble,2307,OH,United States@
Putnam,2308,OH,United States@
Richland,2309,OH,United States@
Ross,2310,OH,United States@
Sandusky,2311,OH,United States@
Scioto,2312,OH,United States@
Seneca,2313,OH,United States@
Shelby,2314,OH,United States@
Stark,2315,OH,United States@
Summit,2316,OH,United States@
Trumbull,2317,OH,United States@
Tuscarawas,2318,OH,United States@
Union,2319,OH,United States@
Van Wert,2320,OH,United States@
Vinton,2321,OH,United States@
Warren,2322,OH,United States@
Washington,2323,OH,United States@
Wayne,2324,OH,United States@
Williams,2325,OH,United States@
Wood,2326,OH,United States@
Wyandot,2327,OH,United States@
Youngstown,33705,OH,United States@
Adair,2328,OK,United States@
Alfalfa,2329,OK,United States@
Atoka,2330,OK,United States@
Bartlesville,50217,OK,United States@
Beaver,2331,OK,United States@
Beckham,2332,OK,United States@
Blaine,2333,OK,United States@
Bryan,2334,OK,United States@
Caddo,2335,OK,United States@
Canadian,2336,OK,United States@
Carter,2337,OK,United States@
Cherokee,2338,OK,United States@
Choctaw,2339,OK,United States@
Cimarron,2340,OK,United States@
Cleveland,2341,OK,United States@
Coal,2342,OK,United States@
Comanche,2343,OK,United States@
Cotton,2344,OK,United States@
Craig,2345,OK,United States@
Creek,2346,OK,United States@
Custer,2347,OK,United States@
Delaware,2348,OK,United States@
Dewey,2349,OK,United States@
Ellis,2350,OK,United States@
Garfield,2351,OK,United States@
Garvin,2352,OK,United States@
Grady,2353,OK,United States@
Grant,2354,OK,United States@
Greer,2355,OK,United States@
Harmon,2356,OK,United States@
Harper,2357,OK,United States@
Haskell,2358,OK,United States@
Hughes,2359,OK,United States@
Jackson,2360,OK,United States@
Jefferson,2361,OK,United States@
Johnston,2362,OK,United States@
Kay,2363,OK,United States@
Kingfisher,2364,OK,United States@
Kiowa,2365,OK,United States@
Latimer,2366,OK,United States@
Le Flore,2367,OK,United States@
Lincoln,2368,OK,United States@
Logan,2369,OK,United States@
Love,2370,OK,United States@
Major,2374,OK,United States@
Marshall,2375,OK,United States@
Mayes,2376,OK,United States@
McClain,2371,OK,United States@
McCurtain,2372,OK,United States@
McIntosh,2373,OK,United States@
Murray,2377,OK,United States@
Muskogee,2378,OK,United States@
Noble,2379,OK,United States@
Nowata,2380,OK,United States@
Okfuskee,2381,OK,United States@
Oklahoma City,3770,OK,United States@
Oklahoma,2382,OK,United States@
Okmulgee,2383,OK,United States@
Osage,2384,OK,United States@
Ottawa,2385,OK,United States@
Pawnee,2386,OK,United States@
Payne,2387,OK,United States@
Pittsburg,2388,OK,United States@
Pontotoc,2389,OK,United States@
Pottawatomie,2390,OK,United States@
Pushmataha,2391,OK,United States@
Roger Mills,2392,OK,United States@
Rogers,2393,OK,United States@
Seminole,2394,OK,United States@
Sequoyah,2395,OK,United States@
Stephens,2396,OK,United States@
Texas,2397,OK,United States@
Tillman,2398,OK,United States@
Tulsa,2399,OK,United States@
Wagoner,2400,OK,United States@
Washington,2401,OK,United States@
Washita,2402,OK,United States@
Woods,2403,OK,United States@
Woodward,2404,OK,United States@
Baker,2405,OR,United States@
Benton,2406,OR,United States@
Clackamas,2407,OR,United States@
Clatsop,2408,OR,United States@
Columbia,2409,OR,United States@
Coos,2410,OR,United States@
Crook,2411,OR,United States@
Curry,2412,OR,United States@
Deschutes,2413,OR,United States@
Douglas,2414,OR,United States@
Gilliam,2415,OR,United States@
Grant,2416,OR,United States@
Harney,2417,OR,United States@
Hood River,2418,OR,United States@
Jackson,2419,OR,United States@
Jefferson,2420,OR,United States@
Josephine,2421,OR,United States@
Klamath,2422,OR,United States@
Lake,2423,OR,United States@
Lane,2424,OR,United States@
Lincoln,2425,OR,United States@
Linn,2426,OR,United States@
Malheur,2427,OR,United States@
Marion,2428,OR,United States@
Morrow,2429,OR,United States@
Multnomah,2430,OR,United States@
Polk,2431,OR,United States@
Portland,3748,OR,United States@
Salem,3771,OR,United States@
Sherman,2432,OR,United States@
Tillamook,2433,OR,United States@
Umatilla,2434,OR,United States@
Union,2435,OR,United States@
Wallowa,2436,OR,United States@
Wasco,2437,OR,United States@
Washington,2438,OR,United States@
Wheeler,2439,OR,United States@
Yamhill,2440,OR,United States@
Adams,2441,PA,United States@
Allegheny,2442,PA,United States@
Armstrong,2443,PA,United States@
Beaver,2444,PA,United States@
Bedford,2445,PA,United States@
Berks,2446,PA,United States@
Blair,2447,PA,United States@
Bradford,2448,PA,United States@
Bucks,2449,PA,United States@
Butler,2450,PA,United States@
Cambria,2451,PA,United States@
Cameron,2452,PA,United States@
Carbon,2453,PA,United States@
Centre,2454,PA,United States@
Chester,2455,PA,United States@
Clarion,2456,PA,United States@
Clearfield,2457,PA,United States@
Clinton,2458,PA,United States@
Columbia,2459,PA,United States@
Crawford,2460,PA,United States@
Cumberland,2461,PA,United States@
Dauphin,2462,PA,United States@
Delaware,2463,PA,United States@
Elk,2464,PA,United States@
Ellwood,33704,PA,United States@
Erie,2465,PA,United States@
Fayette,2466,PA,United States@
Forest,2467,PA,United States@
Franklin,2468,PA,United States@
Fulton,2469,PA,United States@
Greene,2470,PA,United States@
Huntingdon,2471,PA,United States@
Indiana,2472,PA,United States@
Jefferson,2473,PA,United States@
Juniata,2474,PA,United States@
Lackawanna,2475,PA,United States@
Lancaster,2476,PA,United States@
Lawrence,2477,PA,United States@
Lebanon,2478,PA,United States@
Lehigh,2479,PA,United States@
Luzerne,2480,PA,United States@
Lycoming,2481,PA,United States@
Mc Kean,2482,PA,United States@
Mercer,2483,PA,United States@
Mifflin,2484,PA,United States@
Monroe,2485,PA,United States@
Montgomery,2486,PA,United States@
Montour,2487,PA,United States@
Northampton,2488,PA,United States@
Northumberland,2489,PA,United States@
Perry,2490,PA,United States@
Philadelphia,2491,PA,United States@
Pike,2492,PA,United States@
Potter,2493,PA,United States@
Schuylkill,2494,PA,United States@
Snyder,2495,PA,United States@
Somerset,2496,PA,United States@
Sullivan,2497,PA,United States@
Susquehanna,2498,PA,United States@
Tioga,2499,PA,United States@
Union,2500,PA,United States@
Venango,2501,PA,United States@
Warren,2502,PA,United States@
Washington,2503,PA,United States@
Wayne,2504,PA,United States@
Westmoreland,2505,PA,United States@
Wyoming,2506,PA,United States@
York,2507,PA,United States@
Bristol,2508,RI,United States@
Kent,2509,RI,United States@
Newport,2510,RI,United States@
Providence,2511,RI,United States@
Washington,2512,RI,United States@
Abbeville,2513,SC,United States@
Aiken,2514,SC,United States@
Allendale,2515,SC,United States@
Anderson,2516,SC,United States@
Bamberg,2517,SC,United States@
Barnwell,2518,SC,United States@
Beaufort,2519,SC,United States@
Berkeley,2520,SC,United States@
Calhoun,2521,SC,United States@
Charleston,2522,SC,United States@
Cherokee,2523,SC,United States@
Chester,2524,SC,United States@
Chesterfield,2525,SC,United States@
Clarendon,2526,SC,United States@
Colleton,2527,SC,United States@
Darlington,2528,SC,United States@
Dillon,2529,SC,United States@
Dorchester,2530,SC,United States@
Edgefield,2531,SC,United States@
Fairfield,2532,SC,United States@
Florence,2533,SC,United States@
Georgetown,2534,SC,United States@
Greenville,2535,SC,United States@
Greenwood,2536,SC,United States@
Greer,33703,SC,United States@
Hampton,2537,SC,United States@
Horry,2538,SC,United States@
Jasper,2539,SC,United States@
Kershaw,2540,SC,United States@
Lancaster,2541,SC,United States@
Laurens,2542,SC,United States@
Lee,2543,SC,United States@
Lexington,2544,SC,United States@
Marion,2546,SC,United States@
Marlboro,2547,SC,United States@
McCormick,2545,SC,United States@
Newberry,2548,SC,United States@
Oconee,2549,SC,United States@
Orangeburg,2550,SC,United States@
Pickens,2551,SC,United States@
Richland,2552,SC,United States@
Saluda,2553,SC,United States@
Spartanburg,2554,SC,United States@
Sumter,2555,SC,United States@
Union,2556,SC,United States@
Williamsburg,2557,SC,United States@
York,2558,SC,United States@
Aurora,2559,SD,United States@
Beadle,2560,SD,United States@
Bennett,2561,SD,United States@
Bon Homme,2562,SD,United States@
Brookings,2563,SD,United States@
Brown,2564,SD,United States@
Brule,2565,SD,United States@
Buffalo,2566,SD,United States@
Butte,2567,SD,United States@
Campbell,2568,SD,United States@
Charles Mix,2569,SD,United States@
Clark,2570,SD,United States@
Clay,2571,SD,United States@
Codington,2572,SD,United States@
Corson,2573,SD,United States@
Custer,2574,SD,United States@
Davison,2575,SD,United States@
Day,2576,SD,United States@
Deuel,2577,SD,United States@
Dewey,2578,SD,United States@
Douglas,2579,SD,United States@
Edmunds,2580,SD,United States@
Fall River,2581,SD,United States@
Faulk,2582,SD,United States@
Grant,2583,SD,United States@
Gregory,2584,SD,United States@
Haakon,2585,SD,United States@
Hamlin,2586,SD,United States@
Hand,2587,SD,United States@
Hanson,2588,SD,United States@
Harding,2589,SD,United States@
Hughes,2590,SD,United States@
Hutchinson,2591,SD,United States@
Hyde,2592,SD,United States@
Jackson,2593,SD,United States@
Jerauld,2594,SD,United States@
Jones,2595,SD,United States@
Kingsbury,2596,SD,United States@
Lake,2597,SD,United States@
Lawrence,2598,SD,United States@
Lincoln,2599,SD,United States@
Lyman,2600,SD,United States@
Marshall,2603,SD,United States@
McCook,2601,SD,United States@
McPherson,2602,SD,United States@
Meade,2604,SD,United States@
Mellette,2605,SD,United States@
Miner,2606,SD,United States@
Minnehaha,2607,SD,United States@
Moody,2608,SD,United States@
Pennington,2609,SD,United States@
Perkins,2610,SD,United States@
Potter,2611,SD,United States@
Roberts,2612,SD,United States@
Sanborn,2613,SD,United States@
Shannon,2614,SD,United States@
Sioux Falls,33745,SD,United States@
Spink,2615,SD,United States@
Stanley,2616,SD,United States@
Sully,2617,SD,United States@
Todd,2618,SD,United States@
Tripp,2619,SD,United States@
Turner,2620,SD,United States@
Union,2621,SD,United States@
Walworth,2622,SD,United States@
Yankton,2623,SD,United States@
Ziebach,2624,SD,United States@
Anderson,2625,TN,United States@
Bedford,2626,TN,United States@
Benton,2627,TN,United States@
Bledsoe,2628,TN,United States@
Blount,2629,TN,United States@
Bradley,2630,TN,United States@
Campbell,2631,TN,United States@
Cannon,2632,TN,United States@
Carroll,2633,TN,United States@
Carter,2634,TN,United States@
Cheatham,2635,TN,United States@
Chester,2636,TN,United States@
Claiborne,2637,TN,United States@
Clay,2638,TN,United States@
Cocke,2639,TN,United States@
Coffee,2640,TN,United States@
Crockett,2641,TN,United States@
Cumberland,2642,TN,United States@
Davidson,2643,TN,United States@
Decatur,2644,TN,United States@
DeKalb,2645,TN,United States@
Dickson,2646,TN,United States@
Dyer,2647,TN,United States@
Fayette,2648,TN,United States@
Fentress,2649,TN,United States@
Fort Campbell,56744,TN,United States@
Franklin,2650,TN,United States@
Gibson,2651,TN,United States@
Giles,2652,TN,United States@
Grainger,2653,TN,United States@
Greene,2654,TN,United States@
Grundy,2655,TN,United States@
Hamblen,2656,TN,United States@
Hamilton,2657,TN,United States@
Hancock,2658,TN,United States@
Hardeman,2659,TN,United States@
Hardin,2660,TN,United States@
Hawkins,2661,TN,United States@
Haywood,2662,TN,United States@
Henderson,2663,TN,United States@
Henry,2664,TN,United States@
Hickman,2665,TN,United States@
Houston,2666,TN,United States@
Humphreys,2667,TN,United States@
Jackson,2668,TN,United States@
Jefferson,2669,TN,United States@
Johnson,2670,TN,United States@
Knox,2671,TN,United States@
Lake,2672,TN,United States@
Lauderdale,2673,TN,United States@
Lawrence,2674,TN,United States@
Lewis,2675,TN,United States@
Lincoln,2676,TN,United States@
Loudon,2677,TN,United States@
Macon,2680,TN,United States@
Madison,2681,TN,United States@
Marion,2682,TN,United States@
Marshall,2683,TN,United States@
Maury,2684,TN,United States@
McMinn,2678,TN,United States@
McNairy,2679,TN,United States@
Meigs,2685,TN,United States@
Monroe,2686,TN,United States@
Montgomery,2687,TN,United States@
Moore,2688,TN,United States@
Morgan,2689,TN,United States@
Oak Ridge,33736,TN,United States@
Obion,2690,TN,United States@
Overton,2691,TN,United States@
Perry,2692,TN,United States@
Pickett,2693,TN,United States@
Polk,2694,TN,United States@
Putnam,2695,TN,United States@
Rhea,2696,TN,United States@
Roane,2697,TN,United States@
Robertson,2698,TN,United States@
Rutherford,2699,TN,United States@
Scott,2700,TN,United States@
Sequatchie,2701,TN,United States@
Sevier,2702,TN,United States@
Shelby,2703,TN,United States@
Smith,2704,TN,United States@
Stewart,2705,TN,United States@
Sullivan,2706,TN,United States@
Sumner,2707,TN,United States@
Tipton,2708,TN,United States@
Trousdale,2709,TN,United States@
Tullahoma,33741,TN,United States@
Unicoi,2710,TN,United States@
Union,2711,TN,United States@
Van Buren,2712,TN,United States@
Warren,2713,TN,United States@
Washington,2714,TN,United States@
Wayne,2715,TN,United States@
Weakley,2716,TN,United States@
White,2717,TN,United States@
Williamson,2718,TN,United States@
Wilson,2719,TN,United States@
Abilene,33698,TX,United States@
Amarillo,33715,TX,United States@
Anderson,2720,TX,United States@
Andrews,2721,TX,United States@
Angelina,2722,TX,United States@
Aransas,2723,TX,United States@
Archer,2724,TX,United States@
Arlington,33716,TX,United States@
Armstrong,2725,TX,United States@
Atascosa,2726,TX,United States@
Austin,2727,TX,United States@
Bailey,2728,TX,United States@
Bandera,2729,TX,United States@
Bastrop,2730,TX,United States@
Baylor,2731,TX,United States@
Bee,2732,TX,United States@
Bell,2733,TX,United States@
Bexar,2734,TX,United States@
Blanco,2735,TX,United States@
Borden,2736,TX,United States@
Bosque,2737,TX,United States@
Bowie,2738,TX,United States@
Brazoria,2739,TX,United States@
Brazos,2740,TX,United States@
Brewster,2741,TX,United States@
Briscoe,2742,TX,United States@
Brooks,2743,TX,United States@
Brown,2744,TX,United States@
Burleson,2745,TX,United States@
Burnet,2746,TX,United States@
Caldwell,2747,TX,United States@
Calhoun,2748,TX,United States@
Callahan,2749,TX,United States@
Cameron,2750,TX,United States@
Camp,2751,TX,United States@
Carrolton,33721,TX,United States@
Carson,2752,TX,United States@
Cass,2753,TX,United States@
Castro,2754,TX,United States@
Chambers,2755,TX,United States@
Cherokee,2756,TX,United States@
Childress,2757,TX,United States@
Clay,2758,TX,United States@
Cochran,2759,TX,United States@
Coke,2760,TX,United States@
Coleman,2761,TX,United States@
Collin,2762,TX,United States@
Collingsworth,2763,TX,United States@
Colorado,2764,TX,United States@
Comal,2765,TX,United States@
Comanche,2766,TX,United States@
Concho,2767,TX,United States@
Cooke,2768,TX,United States@
Coryell,2769,TX,United States@
Cottle,2770,TX,United States@
Crane,2771,TX,United States@
Crockett,2772,TX,United States@
Crosby,2773,TX,United States@
Culberson,2774,TX,United States@
Dallam,2775,TX,United States@
Dallas,2776,TX,United States@
Dawson,2777,TX,United States@
Deaf Smith,2778,TX,United States@
Delta,2779,TX,United States@
Denton,2780,TX,United States@
DeWitt,2781,TX,United States@
Dickens,2782,TX,United States@
Dimmit,2783,TX,United States@
Donley,2784,TX,United States@
Duval,2785,TX,United States@
Eastland,2786,TX,United States@
Ector,2787,TX,United States@
Edwards,2788,TX,United States@
El Paso,2790,TX,United States@
Ellis,2789,TX,United States@
Erath,2791,TX,United States@
Falls,2792,TX,United States@
Fannin,2793,TX,United States@
Fayette,2794,TX,United States@
Fisher,2795,TX,United States@
Floyd,2796,TX,United States@
Foard,2797,TX,United States@
Fort Bend,2798,TX,United States@
Fort Worth,33699,TX,United States@
Franklin,2799,TX,United States@
Freestone,2800,TX,United States@
Frio,2801,TX,United States@
Gaines,2802,TX,United States@
Galveston,2803,TX,United States@
Garza,2804,TX,United States@
Gillespie,2805,TX,United States@
Glasscock,2806,TX,United States@
Goliad,2807,TX,United States@
Gonzales,2808,TX,United States@
Grand Prairie,33726,TX,United States@
Gray,2809,TX,United States@
Grayson,2810,TX,United States@
Gregg,2811,TX,United States@
Grimes,2812,TX,United States@
Guadalupe,2813,TX,United States@
Hale,2814,TX,United States@
Hall,2815,TX,United States@
Hamilton,2816,TX,United States@
Hansford,2817,TX,United States@
Hardeman,2818,TX,United States@
Hardin,2819,TX,United States@
Harris,2820,TX,United States@
Harrison,2821,TX,United States@
Hartley,2822,TX,United States@
Haskell,2823,TX,United States@
Hays,2824,TX,United States@
Hemphill,2825,TX,United States@
Henderson,2826,TX,United States@
Hidalgo,2827,TX,United States@
Hill,2828,TX,United States@
Hockley,2829,TX,United States@
Hood,2830,TX,United States@
Hopkins,2831,TX,United States@
Houston,2832,TX,United States@
Howard,2833,TX,United States@
Hudspeth,2834,TX,United States@
Hunt,2835,TX,United States@
Hutchinson,2836,TX,United States@
Irion,2837,TX,United States@
Jack,2838,TX,United States@
Jackson,2839,TX,United States@
Jasper,2840,TX,United States@
Jeff Davis,2841,TX,United States@
Jefferson,2842,TX,United States@
Jim Hogg,2843,TX,United States@
Jim Wells,2844,TX,United States@
Johnson,2845,TX,United States@
Jones,2846,TX,United States@
Karnes,2847,TX,United States@
Kaufman,2848,TX,United States@
Kendall,2849,TX,United States@
Kenedy,2850,TX,United States@
Kent,2851,TX,United States@
Kerr,2852,TX,United States@
Kimble,2853,TX,United States@
King,2854,TX,United States@
Kinney,2855,TX,United States@
Kleberg,2856,TX,United States@
Knox,2857,TX,United States@
La Salle,2861,TX,United States@
Lamar,2858,TX,United States@
Lamb,2859,TX,United States@
Lampasas,2860,TX,United States@
Lavaca,2862,TX,United States@
Lee,2863,TX,United States@
Leon,2864,TX,United States@
Liberty,2865,TX,United States@
Limestone,2866,TX,United States@
Lipscomb,2867,TX,United States@
Live Oak,2868,TX,United States@
Llano,2869,TX,United States@
Loving,2870,TX,United States@
Lubbock,2871,TX,United States@
Lynn,2872,TX,United States@
Madison,2876,TX,United States@
Marion,2877,TX,United States@
Martin,2878,TX,United States@
Mason,2879,TX,United States@
Matagorda,2880,TX,United States@
Maverick,2881,TX,United States@
McCulloch,2873,TX,United States@
McLennan,2874,TX,United States@
McMullen,2875,TX,United States@
Medina,2882,TX,United States@
Menard,2883,TX,United States@
Midland,2884,TX,United States@
Milam,2885,TX,United States@
Mills,2886,TX,United States@
Mitchell,2887,TX,United States@
Montague,2888,TX,United States@
Montgomery,2889,TX,United States@
Moore,2890,TX,United States@
Morris,2891,TX,United States@
Motley,2892,TX,United States@
Nacogdoches,2893,TX,United States@
Navarro,2894,TX,United States@
Newton,2895,TX,United States@
Nolan,2896,TX,United States@
Nueces,2897,TX,United States@
Ochiltree,2898,TX,United States@
Oldham,2899,TX,United States@
Orange,2900,TX,United States@
Palo Pinto,2901,TX,United States@
Panola,2902,TX,United States@
Parker,2903,TX,United States@
Parmer,2904,TX,United States@
Pecos,2905,TX,United States@
Polk,2906,TX,United States@
Potter,2907,TX,United States@
Presidio,2908,TX,United States@
Rains,2909,TX,United States@
Randall,2910,TX,United States@
Reagan,2911,TX,United States@
Real,2912,TX,United States@
Red River,2913,TX,United States@
Reeves,2914,TX,United States@
Refugio,2915,TX,United States@
Richardson City,33737,TX,United States@
Roberts,2916,TX,United States@
Robertson,2917,TX,United States@
Rockwall,2918,TX,United States@
Runnels,2919,TX,United States@
Rusk,2920,TX,United States@
Sabine,2921,TX,United States@
San Augustine,2922,TX,United States@
San Jacinto,2923,TX,United States@
San Patricio,2924,TX,United States@
San Saba,2925,TX,United States@
Schleicher,2926,TX,United States@
Scurry,2927,TX,United States@
Shackelford,2928,TX,United States@
Shelby,2929,TX,United States@
Sherman,2930,TX,United States@
Smith,2931,TX,United States@
Somervell,2932,TX,United States@
Starr,2933,TX,United States@
Stephens,2934,TX,United States@
Sterling,2935,TX,United States@
Stonewall,2936,TX,United States@
Sutton,2937,TX,United States@
Swisher,2938,TX,United States@
Tarrant,2939,TX,United States@
Taylor,2940,TX,United States@
Terrell,2941,TX,United States@
Terry,2942,TX,United States@
Texarkana,33702,TX,United States@
Throckmorton,2943,TX,United States@
Titus,2944,TX,United States@
Tom Green,2945,TX,United States@
Travis,2946,TX,United States@
Trinity,2947,TX,United States@
Tyler,2948,TX,United States@
Upshur,2949,TX,United States@
Upton,2950,TX,United States@
Uvalde,2951,TX,United States@
Val Verde,2952,TX,United States@
Van Zandt,2953,TX,United States@
Victoria,2954,TX,United States@
Walker,2955,TX,United States@
Waller,2956,TX,United States@
Ward,2957,TX,United States@
Washington,2958,TX,United States@
Webb,2959,TX,United States@
Wharton,2960,TX,United States@
Wheeler,2961,TX,United States@
Wichita,2962,TX,United States@
Wilbarger,2963,TX,United States@
Willacy,2964,TX,United States@
Williamson,2965,TX,United States@
Wilson,2966,TX,United States@
Winkler,2967,TX,United States@
Wise,2968,TX,United States@
Wood,2969,TX,United States@
Yoakum,2970,TX,United States@
Young,2971,TX,United States@
Zapata,2972,TX,United States@
Zavala,2973,TX,United States@
Beaver,2974,UT,United States@
Box Elder,2975,UT,United States@
Cache,2976,UT,United States@
Carbon,2977,UT,United States@
Daggett,2978,UT,United States@
Davis,2979,UT,United States@
Duchesne,2980,UT,United States@
Emery,2981,UT,United States@
Garfield,2982,UT,United States@
Grand,2983,UT,United States@
Iron,2984,UT,United States@
Juab,2985,UT,United States@
Kane,2986,UT,United States@
Millard,2987,UT,United States@
Morgan,2988,UT,United States@
Piute,2989,UT,United States@
Rich,2990,UT,United States@
Salt Lake,2991,UT,United States@
San Juan,2992,UT,United States@
Sanpete,2993,UT,United States@
Sevier,2994,UT,United States@
Summit,2995,UT,United States@
Tooele,2996,UT,United States@
Uintah,2997,UT,United States@
Utah,2998,UT,United States@
Wasatch,2999,UT,United States@
Washington,3000,UT,United States@
Wayne,3001,UT,United States@
Weber,3002,UT,United States@
Accomack,3003,VA,United States@
Albemarle,3004,VA,United States@
Alexandria,33686,VA,United States@
Alleghany,3005,VA,United States@
Amelia,3006,VA,United States@
Amherst,3007,VA,United States@
Appomattox,3008,VA,United States@
Arlington,3009,VA,United States@
Augusta,3010,VA,United States@
Bath,3011,VA,United States@
Bedford,3012,VA,United States@
Bedford,33651,VA,United States@
Bland,3013,VA,United States@
Botetourt,3014,VA,United States@
Bristol,33652,VA,United States@
Brunswick,3015,VA,United States@
Buchanan,3016,VA,United States@
Buckingham,3017,VA,United States@
Buena Vista,33693,VA,United States@
Campbell,3018,VA,United States@
Caroline,3019,VA,United States@
Carroll,3020,VA,United States@
Charles City,3021,VA,United States@
Charlotte,3022,VA,United States@
Charlottesville,33653,VA,United States@
Chesapeake,33654,VA,United States@
Chesterfield,3023,VA,United States@
Clarke,3024,VA,United States@
Clifton Forge,33655,VA,United States@
Colonial Heights,33656,VA,United States@
Craig,3025,VA,United States@
Culpeper,3026,VA,United States@
Cumberland,3027,VA,United States@
Danville,33657,VA,United States@
Dickenson,3028,VA,United States@
Dinwiddie,3029,VA,United States@
Emporia,33658,VA,United States@
Essex,3030,VA,United States@
Fairfax,3031,VA,United States@
Fairfax,33659,VA,United States@
Falls Church,33660,VA,United States@
Fauquier,3032,VA,United States@
Floyd,3033,VA,United States@
Fluvanna,3034,VA,United States@
Franklin,3035,VA,United States@
Franklin,33661,VA,United States@
Frederick,3036,VA,United States@
Fredericksburg,33662,VA,United States@
Galax,33694,VA,United States@
Giles,3037,VA,United States@
Gloucester,3038,VA,United States@
Goochland,3039,VA,United States@
Grayson,3040,VA,United States@
Greene,3041,VA,United States@
Greensville,3042,VA,United States@
Halifax,3043,VA,United States@
Hampton,33663,VA,United States@
Hanover,3044,VA,United States@
Harrisonburg,33664,VA,United States@
Henrico,3045,VA,United States@
Henry,3046,VA,United States@
Highland,3047,VA,United States@
Hopewell,33665,VA,United States@
Isle of Wight,3048,VA,United States@
James City,3049,VA,United States@
King and Queen,3050,VA,United States@
King George,3051,VA,United States@
King William,3052,VA,United States@
Lancaster,3053,VA,United States@
Lee,3054,VA,United States@
Lexington,33666,VA,United States@
Loudoun,3055,VA,United States@
Louisa,3056,VA,United States@
Lunenburg,3057,VA,United States@
Lynchburg,33667,VA,United States@
Madison,3058,VA,United States@
Manassas Park,33700,VA,United States@
Manassas,33668,VA,United States@
Martinsville,33669,VA,United States@
Mathews,3059,VA,United States@
Mecklenburg,3060,VA,United States@
Middlesex,3061,VA,United States@
Montgomery,3062,VA,United States@
Nelson,3063,VA,United States@
New Kent,3064,VA,United States@
Newport News,33670,VA,United States@
Norfolk,33671,VA,United States@
Northampton,3065,VA,United States@
Northumberland,3066,VA,United States@
Norton,33684,VA,United States@
Nottoway,3067,VA,United States@
Orange,3068,VA,United States@
Page,3069,VA,United States@
Patrick,3070,VA,United States@
Petersburg,33672,VA,United States@
Pittsylvania,3071,VA,United States@
Poquoson,33674,VA,United States@
Portsmouth,33675,VA,United States@
Powhatan,3072,VA,United States@
Prince Edward,3073,VA,United States@
Prince George,3074,VA,United States@
Prince William,3075,VA,United States@
Pulaski,3076,VA,United States@
Rappahannock,3077,VA,United States@
Richmond,3078,VA,United States@
Richmond,3780,VA,United States@
Roanoke,3079,VA,United States@
Roanoke,33678,VA,United States@
Rockbridge,3080,VA,United States@
Rockingham,3081,VA,United States@
Russell,3082,VA,United States@
Salem,33679,VA,United States@
Scott,3083,VA,United States@
Shenandoah,3084,VA,United States@
Smyth,3085,VA,United States@
South Boston,33695,VA,United States@
Southampton,3086,VA,United States@
Spotsylvania,3087,VA,United States@
Stafford,3088,VA,United States@
Staunton,33680,VA,United States@
Suffolk,33681,VA,United States@
Surry,3089,VA,United States@
Sussex,3090,VA,United States@
Tazewell,3091,VA,United States@
Virginia Beach,33701,VA,United States@
Warren,3092,VA,United States@
Washington,3093,VA,United States@
Waynesboro,33687,VA,United States@
Westmoreland,3094,VA,United States@
Williamsburg,33683,VA,United States@
Winchester,33685,VA,United States@
Wise,3095,VA,United States@
Wythe,3096,VA,United States@
York,3097,VA,United States@
Addison,3098,VT,United States@
Bennington,3099,VT,United States@
Caledonia,3100,VT,United States@
Chittenden,3101,VT,United States@
Essex,3102,VT,United States@
Franklin,3103,VT,United States@
Grand Isle,3104,VT,United States@
Lamoille,3105,VT,United States@
Orange,3106,VT,United States@
Orleans,3107,VT,United States@
Rutland,3108,VT,United States@
Washington,3109,VT,United States@
Windham,3110,VT,United States@
Windsor,3111,VT,United States@
Adams,3112,WA,United States@
Asotin,3113,WA,United States@
Benton,3114,WA,United States@
Chelan,3115,WA,United States@
Clallam,3116,WA,United States@
Clark,3117,WA,United States@
Columbia,3118,WA,United States@
Cowlitz,3119,WA,United States@
Douglas,3120,WA,United States@
Ferry,3121,WA,United States@
Franklin,3122,WA,United States@
Garfield,3123,WA,United States@
Grant,3124,WA,United States@
Grays Harbor,3125,WA,United States@
Island,3126,WA,United States@
Jefferson,3127,WA,United States@
King,3128,WA,United States@
Kitsap,3129,WA,United States@
Kittitas,3130,WA,United States@
Klickitat,3131,WA,United States@
Lewis,3132,WA,United States@
Lincoln,3133,WA,United States@
Mason,3134,WA,United States@
Okanogan,3135,WA,United States@
Pacific,3136,WA,United States@
Pend Oreille,3137,WA,United States@
Pierce,3138,WA,United States@
San Juan,3139,WA,United States@
Skagit,3140,WA,United States@
Skamania,3141,WA,United States@
Snohomish,3142,WA,United States@
Spokane,3143,WA,United States@
Stevens,3144,WA,United States@
Thurston,3145,WA,United States@
Wahkiakum,3146,WA,United States@
Walla Walla,3147,WA,United States@
Whatcom,3148,WA,United States@
Whitman,3149,WA,United States@
Yakima,3150,WA,United States@
Adams,3151,WI,United States@
Appleton,33717,WI,United States@
Ashland,3152,WI,United States@
Barron,3153,WI,United States@
Bayfield,3154,WI,United States@
Brown,3155,WI,United States@
Buffalo,3156,WI,United States@
Burnett,3157,WI,United States@
Calumet,3158,WI,United States@
Chippewa,3159,WI,United States@
Clark,3160,WI,United States@
Columbia,3161,WI,United States@
Crawford,3162,WI,United States@
Dane,3163,WI,United States@
Dodge,3164,WI,United States@
Door,3165,WI,United States@
Douglas,3166,WI,United States@
Dunn,3167,WI,United States@
Eau Claire,3168,WI,United States@
Eau Claire,33725,WI,United States@
Florence,3169,WI,United States@
Fond du Lac,3170,WI,United States@
Forest,3171,WI,United States@
Grant,3172,WI,United States@
Green Lake,3174,WI,United States@
Green,3173,WI,United States@
Iowa,3175,WI,United States@
Iron,3176,WI,United States@
Jackson,3177,WI,United States@
Jefferson,3178,WI,United States@
Jefferson,33748,WI,United States@
Juneau,3179,WI,United States@
Kenosha,3180,WI,United States@
Kewaunee,3181,WI,United States@
La Crosse,3182,WI,United States@
Lafayette,3183,WI,United States@
Langlade,3184,WI,United States@
Lincoln,3185,WI,United States@
Manitowoc,3186,WI,United States@
Marathon,3187,WI,United States@
Marinette,3188,WI,United States@
Marquette,3189,WI,United States@
Marshfield,33734,WI,United States@
Menominee,3190,WI,United States@
Milwaukee,3191,WI,United States@
Monroe,3192,WI,United States@
Oconto,3193,WI,United States@
Oneida,3194,WI,United States@
Outagamie,3195,WI,United States@
Ozaukee,3196,WI,United States@
Pepin,3197,WI,United States@
Pierce,3198,WI,United States@
Polk,3199,WI,United States@
Portage,3200,WI,United States@
Price,3201,WI,United States@
Racine,3202,WI,United States@
Richland,3203,WI,United States@
Rock,3204,WI,United States@
Rusk,3205,WI,United States@
Sauk,3207,WI,United States@
Sawyer,3208,WI,United States@
Shawano,3209,WI,United States@
Sheboygan,3210,WI,United States@
St. Croix,3206,WI,United States@
Taylor,3211,WI,United States@
Trempealeau,3212,WI,United States@
Vernon,3213,WI,United States@
Vilas,3214,WI,United States@
Walworth,3215,WI,United States@
Washburn,3216,WI,United States@
Washington,3217,WI,United States@
Watertown,56239,Wi,United States@
Waukesha,3218,WI,United States@
Waupaca,3219,WI,United States@
Waushara,3220,WI,United States@
Winnebago,3221,WI,United States@
Wood,3222,WI,United States@
Barbour,3223,WV,United States@
Berkeley,3224,WV,United States@
Bluefield,33720,WV,United States@
Boone,3225,WV,United States@
Braxton,3226,WV,United States@
Brooke,3227,WV,United States@
Cabell,3228,WV,United States@
Calhoun,3229,WV,United States@
Clay,3230,WV,United States@
Doddridge,3231,WV,United States@
Fayette,3232,WV,United States@
Gilmer,3233,WV,United States@
Grant,3234,WV,United States@
Greenbrier,3235,WV,United States@
Hampshire,3236,WV,United States@
Hancock,3237,WV,United States@
Hardy,3238,WV,United States@
Harrison,3239,WV,United States@
Huntington,33730,WV,United States@
Jackson,3240,WV,United States@
Jefferson,3241,WV,United States@
Kanawha,3242,WV,United States@
Lewis,3243,WV,United States@
Lincoln,3244,WV,United States@
Logan,3245,WV,United States@
Marion,3247,WV,United States@
Marshall,3248,WV,United States@
Mason,3249,WV,United States@
McDowell,3246,WV,United States@
Mercer,3250,WV,United States@
Mineral,3251,WV,United States@
Mingo,3252,WV,United States@
Monongalia,3253,WV,United States@
Monroe,3254,WV,United States@
Morgan,3255,WV,United States@
Nicholas,3256,WV,United States@
Ohio,3257,WV,United States@
Pendleton,3258,WV,United States@
Pleasants,3259,WV,United States@
Pocahontas,3260,WV,United States@
Preston,3261,WV,United States@
Putnam,3262,WV,United States@
Raleigh,3263,WV,United States@
Randolph,3264,WV,United States@
Ritchie,3265,WV,United States@
Roane,3266,WV,United States@
Summers,3267,WV,United States@
Taylor,3268,WV,United States@
Tucker,3269,WV,United States@
Tyler,3270,WV,United States@
Upshur,3271,WV,United States@
Wayne,3272,WV,United States@
Webster,3273,WV,United States@
Weirton,33742,WV,United States@
Wetzel,3274,WV,United States@
Wirt,3275,WV,United States@
Wood,3276,WV,United States@
Wyoming,3277,WV,United States@
Albany,3278,WY,United States@
Big Horn,3279,WY,United States@
Campbell,3280,WY,United States@
Carbon,3281,WY,United States@
Converse,3282,WY,United States@
Crook,3283,WY,United States@
Fremont,3284,WY,United States@
Goshen,3285,WY,United States@
Hot Springs,3286,WY,United States@
Johnson,3287,WY,United States@
Laramie,3288,WY,United States@
Lincoln,3289,WY,United States@
Natrona,3290,WY,United States@
Niobrara,3291,WY,United States@
Park,3292,WY,United States@
Platte,3293,WY,United States@
Sheridan,3294,WY,United States@
Sublette,3295,WY,United States@
Sweetwater,3296,WY,United States@
Teton,3297,WY,United States@
Uinta,3298,WY,United States@
Washakie,3299,WY,United States@
Weston,3300,WY,United States@
Division No. 1,33363,AB,Canada@
Division No. 10,33372,AB,Canada@
Division No. 11,33373,AB,Canada@
Division No. 12,33374,AB,Canada@
Division No. 13,33375,AB,Canada@
Division No. 14,33376,AB,Canada@
Division No. 15,33377,AB,Canada@
Division No. 16,33378,AB,Canada@
Division No. 17,33379,AB,Canada@
Division No. 18,33380,AB,Canada@
Division No. 19,33381,AB,Canada@
Division No. 2,33364,AB,Canada@
Division No. 3,33365,AB,Canada@
Division No. 4,33366,AB,Canada@
Division No. 5,33367,AB,Canada@
Division No. 6,33368,AB,Canada@
Division No. 7,33369,AB,Canada@
Division No. 8,33370,AB,Canada@
Division No. 9,33371,AB,Canada@
Alberni-Clayoquot Regional District,33391,BC,Canada@
Bulkley-Nechako Regional District,33405,BC,Canada@
Capital Regional District,33388,BC,Canada@
Cariboo Regional District,33400,BC,Canada@
Central Coast Regional District,33402,BC,Canada@
Central Fraser Valley,33386,BC,Canada@
Central Kootenay Regional District,33383,BC,Canada@
Central Okanagan Regional District,33397,BC,Canada@
Columbia-Shuswap Regional District,33399,BC,Canada@
Comox-Strathcona Regional District,33392,BC,Canada@
Cowichan Valley Regional District,33389,BC,Canada@
Dewdney-Alouette,33410,BC,Canada@
East Kootenay Regional District,33382,BC,Canada@
Fort Nelson-Liard Regional District,33409,BC,Canada@
Fraser-Cheam,33411,BC,Canada@
Fraser-Fort George Regional District,33406,BC,Canada@
Greater Vancouver Regional District,33387,BC,Canada@
Kitimat-Stikine Regional District,33404,BC,Canada@
Kootenay Boundary Regional District,33384,BC,Canada@
Mount Waddington Regional District,33401,BC,Canada@
Nanaimo Regional District,33390,BC,Canada@
North Okanagan Regional District,33398,BC,Canada@
Okanagan-Similkameen Regional District,33385,BC,Canada@
Peace River Regional District,33407,BC,Canada@
Powell River Regional District,33393,BC,Canada@
Skeena-Queen Charlotte Regional District,33403,BC,Canada@
Squamish-Lillooet Regional District,33395,BC,Canada@
Stikine Region,33408,BC,Canada@
Sunshine Coast Regional District,33394,BC,Canada@
Thompson-Nicola Regional District,33396,BC,Canada@
Division No. 1,33412,MB,Canada@
Division No. 10,33421,MB,Canada@
Division No. 11,33422,MB,Canada@
Division No. 12,33423,MB,Canada@
Division No. 13,33424,MB,Canada@
Division No. 14,33425,MB,Canada@
Division No. 15,33426,MB,Canada@
Division No. 16,33427,MB,Canada@
Division No. 17,33428,MB,Canada@
Division No. 18,33429,MB,Canada@
Division No. 19,33430,MB,Canada@
Division No. 2,33413,MB,Canada@
Division No. 20,33431,MB,Canada@
Division No. 21,33432,MB,Canada@
Division No. 22,33433,MB,Canada@
Division No. 23,33434,MB,Canada@
Division No. 3,33414,MB,Canada@
Division No. 4,33415,MB,Canada@
Division No. 5,33416,MB,Canada@
Division No. 6,33417,MB,Canada@
Division No. 7,33418,MB,Canada@
Division No. 8,33419,MB,Canada@
Division No. 9,33420,MB,Canada@
Albert,33458,NB,Canada@
Carlton,33463,NB,Canada@
Charlotte,33454,NB,Canada@
Gloucester,33467,NB,Canada@
Kent,33460,NB,Canada@
Kings,33457,NB,Canada@
Madawaska,33465,NB,Canada@
Northcumberland,33461,NB,Canada@
Queens,33456,NB,Canada@
Restigouche,33466,NB,Canada@
Saint John,33453,NB,Canada@
Sunbury,33455,NB,Canada@
Victoria,33464,NB,Canada@
Westmorland,33459,NB,Canada@
York,33462,NB,Canada@
Division No. 1,33468,NF,Canada@
Division No. 10,33477,NF,Canada@
Division No. 2,33469,NF,Canada@
Division No. 3,33470,NF,Canada@
Division No. 4,33471,NF,Canada@
Division No. 5,33472,NF,Canada@
Division No. 6,33473,NF,Canada@
Division No. 7,33474,NF,Canada@
Division No. 8,33475,NF,Canada@
Division No. 9,33476,NF,Canada@
Annapolis,33482,NS,Canada@
Antigonish,33491,NS,Canada@
Cape Breton,33494,NS,Canada@
Colcheter,33487,NS,Canada@
Cumberland,33488,NS,Canada@
Digby,33480,NS,Canada@
Guysborough,33490,NS,Canada@
Halifax,33486,NS,Canada@
Hants,33485,NS,Canada@
Inverness,33492,NS,Canada@
Kings,33484,NS,Canada@
Lunenburg,33483,NS,Canada@
Pictou,33489,NS,Canada@
Queens,33481,NS,Canada@
Richmond,33493,NS,Canada@
Shelburne,33478,NS,Canada@
Victoria,33495,NS,Canada@
Yarmouth,33479,NS,Canada@
Baffin Region,33496,NT,Canada@
Fort Smith Region,33498,NT,Canada@
Inuvik Region,33499,NT,Canada@
Keewatin Region,33497,NT,Canada@
Kitikmeot Region,33500,NT,Canada@
Nunavut,33353,NU,Canada@
Algoma District,33546,ON,Canada@
Brant,33523,ON,Canada@
Bruce,33533,ON,Canada@
Cochrane District,33545,ON,Canada@
Dufferin,33517,ON,Canada@
Durham Regional Municipality,33513,ON,Canada@
Elgin,33527,ON,Canada@
Essex,33529,ON,Canada@
Frontenac,33506,ON,Canada@
Grey,33534,ON,Canada@
Haldimand-Norfolk,33522,ON,Canada@
Haliburton,33537,ON,Canada@
Halton Regional Municipality,33519,ON,Canada@
Hamilton-Wentworth,33520,ON,Canada@
Hastings,33508,ON,Canada@
Huron,33532,ON,Canada@
Kenora District,33549,ON,Canada@
Kent,33528,ON,Canada@
Lambton,33530,ON,Canada@
Lanark,33505,ON,Canada@
Leeds And Grenville United Counties,33504,ON,Canada@
Lennox & Addington,33507,ON,Canada@
Manitoulin District,33541,ON,Canada@
Middlesex,33531,ON,Canada@
Muskoka District Municipality,33536,ON,Canada@
Niagra Regional Municipality,33521,ON,Canada@
Nipissing District,33539,ON,Canada@
Northumberland,33510,ON,Canada@
Ottawa-Carleton Regional Municipality,33503,ON,Canada@
Oxford,33526,ON,Canada@
Parry Sound District,33540,ON,Canada@
Peel Regional Municipality,33516,ON,Canada@
Perth,33525,ON,Canada@
Peterborough,33511,ON,Canada@
Prescott And Russell United,33502,ON,Canada@
Prince Edward,33509,ON,Canada@
Rainy River District,33548,ON,Canada@
Renfrew,33538,ON,Canada@
Simcoe,33535,ON,Canada@
Stormont,Dundas & Glengarry,33501,ON,Canada@
Sudbury District,33542,ON,Canada@
Sudbury Regional Municipality,33543,ON,Canada@
Thunder Bay District,33547,ON,Canada@
Timiskaming District,33544,ON,Canada@
Toronto Metro Municipality,33515,ON,Canada@
Victoria,33512,ON,Canada@
Waterloo Regional Municipality,33524,ON,Canada@
Wellington,33518,ON,Canada@
York Regional Municipality,33514,ON,Canada@
Kings,33550,PE,Canada@
Prince,33552,PE,Canada@
Queens,33551,PE,Canada@
Abitibi,33640,QC,Canada@
Abitibi-Ouest,33639,QC,Canada@
Acton,33600,QC,Canada@
Antione-labelle,33631,QC,Canada@
Argenteuil,33628,QC,Canada@
Arthabaska,33591,QC,Canada@
Asbestos,33592,QC,Canada@
Avignon,33558,QC,Canada@
Beauce-Sartigan,33581,QC,Canada@
Beauharnois-Salaberry,33622,QC,Canada@
Becancour,33590,QC,Canada@
Bellechasse,33571,QC,Canada@
Bonaventure,33557,QC,Canada@
Brome-Missisquoi,33598,QC,Canada@
Champlain,33610,QC,Canada@
Charlevoix,33568,QC,Canada@
Charlevoix-Est,33567,QC,Canada@
Coaticook,33596,QC,Canada@
Communaute Urbaine de l'Outaouais,33633,QC,Canada@
Communaute Urbaine de Montréal,33618,QC,Canada@
Communaute Urbaine de Québec,33711,QC,Canada@
D'autray,33604,QC,Canada@
Denis-Riverin,33556,QC,Canada@
Desjardins,33576,QC,Canada@
Deux-Montagnes,33624,QC,Canada@
Drummond,33601,QC,Canada@
Francheville,33589,QC,Canada@
Joliette,33613,QC,Canada@
Kamouraska,33566,QC,Canada@
L'Amiante,33583,QC,Canada@
L'assomption,33612,QC,Canada@
L'Erable,33584,QC,Canada@
L'islet,33569,QC,Canada@
L'lle-d'Orleans,33572,QC,Canada@
La Cote-de-Beaupre,33573,QC,Canada@
La Cote-de-Gaspe,33555,QC,Canada@
La Haute-Cote-Nord,33647,QC,Canada@
La Haute-Yamaska,33599,QC,Canada@
La Jacques-Cartier,33574,QC,Canada@
La Matapedia,33559,QC,Canada@
La Mitis,33561,QC,Canada@
La Nouvelle-Beauce,33578,QC,Canada@
La Riviere-du-Nord,33627,QC,Canada@
La Vallee-de-la-Gatineau,33635,QC,Canada@
La Vallee-du-Richelieu,33609,QC,Canada@
Lac-Saint-Jean-Est,33645,QC,Canada@
Lajemmarais,33611,QC,Canada@
Laval,33617,QC,Canada@
Le Bas-Richelieu,33605,QC,Canada@
Le Centre-de-la-Maruicie,33588,QC,Canada@
Le Domaine-du-Roy,33643,QC,Canada@
Le Fjord-du-Saguenay,33646,QC,Canada@
Le Granit,33582,QC,Canada@
Le Haut-Richelieu,33608,QC,Canada@
Le Haut-Saint-Francois,33593,QC,Canada@
Le Haut-Saint-Laurent,33621,QC,Canada@
Le Haut-Saint-Maurice,33642,QC,Canada@
Le Val-Saint-Francois,33594,QC,Canada@
Les Basques,33563,QC,Canada@
Les Chutes-de-la-Chaudiere,33577,QC,Canada@
Les Collines-de-l'Outaouais,33634,QC,Canada@
Les Etchemins,33580,QC,Canada@
Les Iles-de-la-Madeleine,33553,QC,Canada@
LeS Jardins-de-Napierville,33620,QC,Canada@
Les Laurentides,33630,QC,Canada@
Les Maskoutains,33606,QC,Canada@
Les Moulins,33616,QC,Canada@
Les Pays-d'en-Haut,33629,QC,Canada@
Lotbiniere,33585,QC,Canada@
Manicouagan,33648,QC,Canada@
Maria-Chapdelaine,33644,QC,Canada@
Maskinonge,33603,QC,Canada@
Matane,33560,QC,Canada@
Matawinie,33614,QC,Canada@
Mekinac,33587,QC,Canada@
Memphremagog,33597,QC,Canada@
Minganie - Basse-Cote-Nord,33650,QC,Canada@
Mirabel,33626,QC,Canada@
Montcalm,33615,QC,Canada@
Montmagny,33570,QC,Canada@
Nicolet-Yamaska,33602,QC,Canada@
Pabok,33554,QC,Canada@
Papineau,33632,QC,Canada@
Pontiac,33636,QC,Canada@
Portneuf,33586,QC,Canada@
Rimouski-Neigette,33562,QC,Canada@
Riviere-du-Loup,33564,QC,Canada@
Robert-Cliche,33579,QC,Canada@
Rousillion,33619,QC,Canada@
Rouville,33607,QC,Canada@
Rouyn-Noranda,33638,QC,Canada@
Sept-Rivieres - Caniapiscau,33649,QC,Canada@
Sherbrooke,33595,QC,Canada@
Temiscamingue,33637,QC,Canada@
Temiscouata,33565,QC,Canada@
Territoire Nordique,33575,QC,Canada@
Therese-de Blainville,33625,QC,Canada@
Vallee-de-l'Or,33641,QC,Canada@
Vaudreuil-Soulanges,33623,QC,Canada@
Division No. 1,33435,SK,Canada@
Division No. 10,33444,SK,Canada@
Division No. 11,33445,SK,Canada@
Division No. 12,33446,SK,Canada@
Division No. 13,33447,SK,Canada@
Division No. 14,33448,SK,Canada@
Division No. 15,33449,SK,Canada@
Division No. 16,33450,SK,Canada@
Division No. 17,33451,SK,Canada@
Division No. 18,33452,SK,Canada@
Division No. 2,33436,SK,Canada@
Division No. 3,33437,SK,Canada@
Division No. 4,33438,SK,Canada@
Division No. 5,33439,SK,Canada@
Division No. 6,33440,SK,Canada@
Division No. 7,33441,SK,Canada@
Division No. 8,33442,SK,Canada@
Division No. 9,33443,SK,Canada@
Yukon,33351,YT,Canada@